### ISSUE TITLE
Integration can't be found in HACS

### ISSUE THREAD

**Issue by SgtTacooo** [bremor/bureau_of_meteorology#1]
Not sure if this is because I'm not searching the right thing or whatever but I can't seem to find this integration in HACS. Have searched BOM, bureau, meteorology, bremor etc but I can't find the integration anywhere.

**Comment by DavidFW1960** [comment]
Did you add it as a custom repo? It's not a HACS default repo yet
![image](https://user-images.githubusercontent.com/36390762/97500188-46ad1f00-19c3-11eb-8764-483ff8fee201.png)
