### ISSUE TITLE
weather platform?

### ISSUE THREAD

**Issue by hcoohb** [bremor/bureau_of_meteorology#10]
Hi,
First, thanks a lot for your work on this and for sharing it, this is awesome!

I like to use the custom lovelace card: custom:weather-card-chart which I ffind it much easier to read in terms of temperature and rain forecast. That card takes a weather type entity
So I was wondering if there is any technical reason why you did not go the weather platform way? Or would it be hard to implement as well? (I have never looked inside the weather platform before...)

**Comment by bremor** [comment]
Hey mate, it never occurred to me to create a weather entity, there is no reason I didn’t include it. I will look into this, shouldn’t be too hard.

**Comment by hcoohb** [comment]
That would be terrific if possible!

**Comment by bremor** [comment]
Weather platform has been added in release 0.8 - hopefluly all works as intended. If not please let me know
