### ISSUE TITLE
Daylight hours?

### ISSUE THREAD

**Issue by JustDFB** [bremor/bureau_of_meteorology#100]
Hi,
A fantastic integration thank you!
A feature request please - add daylight hours into the forecast. Or just include sunrise/sunset data assuming its available?
Today: 8h 12m sunlight
Tomorrow: 8h 10m sunlight
etc

Thanks!

**Comment by Makin-Things** [comment]
The forecast data from the bom includes sunrise_time and sunset_time (both in UTC time). It doesn't include the daylight hours but a template could calculate that fairly easily.
I could add them sensors but just wondering if it would be best to keep the times as UTC or convert to local time.

**Comment by DavidFW1960** [comment]
leave as UTC. HA will convert to local already.

**Comment by Makin-Things** [comment]
Added in 1.1.2
