### ISSUE TITLE
today's max, isn't the max?

### ISSUE THREAD

**Issue by jonwaland** [bremor/bureau_of_meteorology#102]
I'm in Pymble, and https://weather.bom.gov.au/location/r3grzp4-pymble shows the max for today to be 32, with the overnight min to be 21, and current temp is 29.0

But the integration is setting sensor.bom_today_max to the current temp, rather than the max. and sensor.bom_today_min to 17 - no idea where this comes from.

![image](https://user-images.githubusercontent.com/33437424/154383590-09d05592-ccaf-4f1d-b8a2-27465d66b622.png)
![image](https://user-images.githubusercontent.com/33437424/154383615-160bc459-05f4-4c60-aba8-4fc918f9a935.png)

**Comment by jonwaland** [comment]
embarrassed. sensor.bom_today_max comes from David's BOM weather package.

**Comment by DavidFW1960** [comment]
Yeah. It should be using statistics or average sensor though to return todays actual minimum and maximum for the day when BOM stops publishing the value

**Comment by jonwaland** [comment]
@DavidFW1960 - I had the default that you provide that uses the today_temp_bom', 'max_value' - I've changed to use the other version that uses the BOM forecast **_or_** today_temp_bom', 'max_value'

**Comment by DavidFW1960** [comment]
if you were using statistics I made a change to that yesterday I think because they changed how it works

**Comment by jonwaland** [comment]
lol
