### ISSUE TITLE
short_text_0-7 says unknown after each update

### ISSUE THREAD

**Issue by nthulke** [bremor/bureau_of_meteorology#104]
Hi,

As you can see the short text for my location is showing as unknown which causes my weather card to show incorrectly.

![image](https://user-images.githubusercontent.com/69140718/155112286-c5bd5ffd-c176-48fb-b72a-8b3c8d659ea4.png)

The High and low I need to work out how this card reads that but the short text is the Unknowns as shown:

![image](https://user-images.githubusercontent.com/69140718/155112682-a92dd548-125d-4d24-ba97-b4c3ce703361.png)

Is there something I am missing?

**Comment by Makin-Things** [comment]
For the unknown what location are you using for the sensors? Also you don't say after which update (HA, the integration, the weather card. I can have a look if you provide more info.

For the second problem it has nothing to do with the bom integration and you are better off seeking config help over at
[https://community.home-assistant.io/t/customising-the-bom-weather-and-lovelace-now-in-hacs/123549/1177](url)

**Comment by Makin-Things** [comment]
Closing as no further response forthcoming.
