### ISSUE TITLE
No Air Pressure Entity

### ISSUE THREAD

**Issue by Todd-H-Wilkinson** [bremor/bureau_of_meteorology#107]
Is there supposed to be an Entity for Air Pressure?
Pulling Melbourne data (Olympic Park Observations). BOM publish an Air Pressure reading on their web page observations but I don't see a sensor created for it.
Thanks (and thanks for building this).

**Comment by Makin-Things** [comment]
Unfortunately the bom api being used does not provide any pressure data so it is not possible to create a sensor for it.
