### ISSUE TITLE
API Copyright Notice

### ISSUE THREAD

**Issue by bremor** [bremor/bureau_of_meteorology#109]
Hey All,

I have only just noticed that the BOM API now returns a copyright notice with each request (see below), I'm not sure when this started. I'm not sure If I feel comfortable continuing to offer/support this integration for use when it is explicitly disallowed by BoM. I'm happy to discuss the best way forward with anyone who is interested.

https://api.weather.bom.gov.au/v1/locations/1r0fup/observations
`This Application Programming Interface (API) is owned by the Bureau of Meteorology (Bureau). You must not use, copy or share this API without express permission from the Bureau. Please contact us for more information. Follow this link http://www.bom.gov.au/inside/contacts.shtml to view our contact details.`

**Comment by Makin-Things** [comment]
That is really dumb. The API as they call it is an HTTP request which they have no authority to copyright. The data itself could have a copyright applied, but their charter dictates that certain data is publicly available. It seems really stupid as the same data I can download using ftp and that is perfectly acceptable. It sounds like someone in the legal department was having a slow day and decided that everything needed a copyright message attached.
Personally I would ignore it since there is nothing they can do, and there is no way for them to determine if the request is from their app or something else.

**Comment by bremor** [comment]
I must say I agree with you, how can an API be copyrighted. Doesn't make any sense to me.

**Comment by Makin-Things** [comment]
Also fun fact. If I was to leave a browser window open on the weather page (and I do) that copyright shit adds 300MB per year of extra downloaded data for no purpose.

**Comment by dexn** [comment]
As far as I know, copyright law doesn't protect function. You're not copying their API, just retrieving data using it's function. Also I believe that since it's not secured, it's fair game. I'm no lawyer though.

**Comment by MasterCATZ** [comment]
When they replied back to me they said it should not be doing that and it was caused by using a VPN ? 
my guess its because my ISP is using NZ IP4 blocks 

```
In reply please quote: CAS-30971-K6W6X0  

Date: 3/05/2022

Dear Christopher,

Thank you for your enquiry.

We are aware of recent issues with using a VPN and accessing the Bureau website and we are investigating. In the meantime, please disable VPN while accessing the Bureau website and let us know if this fixes the problem.

Kind regards,

Lachlan
Weather Connect
Bureau of Meteorology

Phone: 1300 754 389, option 2
```

**Comment by Makin-Things** [comment]
Closing since I think we have agreed to ignore this message for now. Brendan if you don't feel comfortable hosting it on your github account I am happy to host it, but that would complicate things as we would need to update the HACS registry and possibly cause issues for people that have it installed.

**Comment by MasterCATZ** [comment]
Got another message from them , apparently the API is not for public use , its their for the mobile website 

```
Thank you for your enquiry and sorry for the delay in response.
 
I am afraid the API you found, which drives our mobile-friendly web page www.weather.bom.gov.au, is not intended for direct access.  The Bureau is moving towards making APIs available, but we don't yet have a definite timeframe for this.
 
In the meantime, you are welcome to access anonymous FTP for observations to automate your home watering system e.g. IDV60910 Observations – VIC – 72 hour history here: ftp://ftp.bom.gov.au/anon/gen/fwo/IDV60910.tgz
Please see the user guide here: http://reg.bom.gov.au/catalogue/72_hr_historical_obs.pdf
Or            
IDV60920 Observations – VIC – 10 min updates: ftp://ftp.bom.gov.au/anon/gen/fwo/IDV60920.xml
Please see the user guide here: http://reg.bom.gov.au/catalogue/Observations-XML.pdf
 
The Bureau's anonymous FTP service is free to access, subject to the terms of the Bureau's copyright notice: http://www.bom.gov.au/other/copyright.shtml  
i.e. "If there are no specific terms of use, you can download, copy and use that content for personal use, or use within your organisation. You must not supply it to any other person or use it for any commercial purpose." 
 
More information about the anonymous FTP service can be found here: http://reg.bom.gov.au/catalogue/data-feeds.shtml.

 
Kind Regards,

Claire Hawksworth | Meteorologist

```

**Comment by Makin-Things** [comment]
So depending on who responds you get a different answer. I might ask them and see if I get a 3rd different answer.
Also there is no mention of how to get forecast info as I don't believe that is available from the ftp site.

**Comment by DavidFW1960** [comment]
The middle finger would be my response to all that.
The FTP component we were using before this does include forecast but not observations which is why the original BOM component did scraping.

**Comment by Makin-Things** [comment]
Ok, the ftp observations are available as well. I now because I wrote software that pulls those nationwide and publishes them on a cloud based mqtt server. I don't use observations from this integration because what I have is more responsive.
