### ISSUE TITLE
Pull Request to add into HASS Core

### ISSUE THREAD

**Issue by HarrisonPace** [bremor/bureau_of_meteorology#11]
With the existing native integration removed in 0.117, it would be nice to merge this integration into Hass core so new users who are unfamiliar with HACS and custom components can use this component. In general, it would be nice to have a native Bureau of Meteorology integration in HASS. I am happy to assist with this process. 

Thoughts?

**Comment by bremor** [comment]
I would love to get this into HASS core. I have read through the process including getting parts of it into pypi and it’s a bit beyond me, so I would love some help with this process.

**Comment by hell1337hound** [comment]
+1
