### ISSUE TITLE
Rain amout range 0-7?

### ISSUE THREAD

**Issue by Shammy01011101** [bremor/bureau_of_meteorology#112]
In my entities list, I have 8 different Rain sensors and 8 different fire dange sensors.  

I'm looking at having a chart on my dashboard which shows how much rain has fallen, I'm unsure which rain sensor to use since they all appear to be giving different numbers.  My question is what does each version mean/represent?

![Capture](https://user-images.githubusercontent.com/89975338/162601088-a0af2f13-1006-4c8e-bb28-87b93ca0b2ee.png)

**Comment by DavidFW1960** [comment]
They are forecasts for upcoming days. Look for rain since 9am for todays rainfall

**Comment by Makin-Things** [comment]
As David said, these are the forecast values whereas the actual rainfall is in {location}_rain_since_9am.
