### ISSUE TITLE
MDI icons

### ISSUE THREAD

**Issue by neponn** [bremor/bureau_of_meteorology#12]
Hi bremor - I'm totally wrapt that you put this together so quickly. It works very nicely. Just one request for me: the original core bom integration included weather icon sensors that mapped to MDI icons. This made it very easy to display the correct icon for the day. But your integration uses something else. Is it possible to use the MDI icon format in the icon sensors?

**Comment by oneseventhree** [comment]
+1! Great integration. 
I use Dark Sky for the icon's and would love to make the switch as my tileboard doesn't show anything when using this integrations icon:


DarkSky:
<img width="323" alt="Screen Shot 2020-10-31 at 1 56 55 pm" src="https://user-images.githubusercontent.com/15043282/97769657-05626e00-1b81-11eb-8e21-bf20ac00ecb9.png">

BOM:
<img width="315" alt="Screen Shot 2020-10-31 at 1 57 09 pm" src="https://user-images.githubusercontent.com/15043282/97769661-098e8b80-1b81-11eb-9aaf-15aa7d99b312.png">

**Comment by bremor** [comment]
No worries, leave it with me 👍 
What was the format of the sensor state on the old platform? Was it for example “sunny” or “mdi:sunny”

**Comment by neponn** [comment]
Awesome. It was the latter: “mdi:sunny”.

**Comment by bremor** [comment]
I'm working on this now guys, I need to create a "map", to map BOMs values to MDI Icons, so far I have the below. If you could please help up by letting me know what BOM icons you have come across.

MDI_ICON_MAP = {
    "cloudy": "mdi:weather-cloudy",
    "light_shower": "mdi:weather-partly-rainy",
    "sunny": "mdi:weather-sunny",
    "windy": "mdi:weather-windy",
}

**Comment by DavidFW1960** [comment]
Someone asked me for these in the old ftp component but I couldn't get it to use a variable mapping. The numbers are the BOM available conditions

```
ICON_MAPPING = {
    '1': 'mdi:weather-sunny',
    '2': 'mdi:weather-night',
    '3': 'mdi:weather-partly-cloudy',
    '4': 'mdi:weather-cloudy',
    '6': 'mdi:weather-sunset',
    '8': 'mdi:weather-partly-rainy',
    '9': 'mdi:weather-windy',
    '10': 'mdi:weather-sunset',
    '11': 'mdi:weather-rainy',
    '12': 'mdi:weather-pouring',
    '13': 'mdi:weather-sunset',
    '14': 'mdi:snowflake-melt',
    '15': 'mdi:weather-snowy',
    '16': 'mdi:weather-lightning',
    '17': 'mdi:weather-light-showers',
    '18': 'mdi:weather-pouring',
    '19': 'mdi:weather-hurricane'
}
```

**Comment by bremor** [comment]
And here are all the possible values for the new BOM API, fortunately the numbers match up with the FTP component.
```
sunny=1
clear=2
partly_cloudy=3
cloudy=4
mostly_sunny=5
haze=6
hazy=6
light_rain=8
wind=9
windy=9
fog=10
shower=11
showers=11
rain=12
dust=13
dusty=13
frost=14
snow=15
storm=16
storms=16
light_shower=17
light_showers=17
heavy_shower=18
heavy_showers=18
tropical_cyclone=19
cyclone=19
```

**Comment by DavidFW1960** [comment]
yeah. They are published by BOM in a doc I found

**Comment by bremor** [comment]
mdi icons added in v0.7

**Comment by neponn** [comment]
Sensational - thanks @bremor.
