### ISSUE TITLE
New Weather Entities Created and Old Entities Orphaned

### ISSUE THREAD

**Issue by Daneish** [bremor/bureau_of_meteorology#120]
It appears that v1.1.6 of the BOM integration has created new weather entities and my old entities are orphaned. 

I had two entities with `entity_id` in the format weather.suburb and weather.suburb_hourly, these are now orphaned and two new entities have been created with the ids weather.home_2 and weather.home_hourly_2. Note, the _2 is somewhat expected as I have other entities from another integration named weather.home.

I also note that the `friendly_name` of the new entities is `home` and `home Hourly`, not using the expected title case.

All of the BOM sensor entities are unaffected.

I'm happy to just rename my entities and remove the old ones, but I thought I would raise an issue as there wasn't any mention of any breaking changes, and I thought this might not be expected behaviour and could be effecting others.

I'm fairly sure I was running 1.1.5 before without any problems. There are no relevant errors in the Core logs. and restarting Core makes no difference.

Thanks for all your work making this great integration! Let me know if I can provide any more information or 
help to test.

## System Health

version | core-2022.5.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.103-v8
arch | aarch64
timezone | Australia/Sydney

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.24.5
Stage | running
Available Repositories | 1057
Downloaded Repositories | 18

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 29 May 2022, 10:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | ap-southeast-1-0.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.6
-- | --
update_channel | stable
supervisor_version | supervisor-2022.05.1
docker_version | 20.10.9
disk_total | 116.7 GB
disk_used | 71.0 GB
healthy | true
supported | failed to load: Unsupported
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), Samba share (9.6.1), Check Home Assistant configuration (3.10.0), Terminal & SSH (9.4.0), AdGuard Home (4.5.1), Portainer (2.0.0), Home Assistant Google Drive Backup (0.107.2), Studio Code Server (5.0.2), Mosquitto broker (6.1.2), Eufy Security Add-on (0.8.4), RTSP Simple Server Add-on (v0.17.6), Duck DNS (1.14.0), Scrypted (v0.0.177)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 4
views | 19
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by Makin-Things** [comment]
This should not be happening, but I have been able to reproduce. I have temporarily remove 1.1.6 until we can resolve. You should be able to redownload 1.1.5 and it should fix things. Thanks for reporting this.

@glenn20 are you able to have a look at this. It appears that when you upgrade to 1.1.6 it doesn't have a weather_name in the config so it creates 'weather.home' and 'weather.home_hourly'.

**Comment by glenn20** [comment]
> This should not be happening, but I have been able to reproduce. I have temporarily remove 1.1.6 until we can resolve. You should be able to redownload 1.1.5 and it should fix things. Thanks for reporting this.
> 
> @glenn20 are you able to have a look at this. It appears that when you upgrade to 1.1.6 it doesn't have a weather_name in the config so it creates 'weather.home' and 'weather.home_hourly'.

OK - onto it now. The integration falls back to "home" if no name is set through the config flow (this is where previous versions were crashing). However, I "thought" I had ensured a name was always set in the config flow. I'll check it now.

**Comment by Makin-Things** [comment]
I think we should actually do a config migration to V2 with something like this in the config flow.

```
   async def async_migrate_entry(hass, config_entry: ConfigEntry):
        """Migrate old entry."""
        _LOGGER.debug("Migrating from version %s", config_entry.version)

        if config_entry.version == 1:

            new = {**config_entry.data}
            if CONF_FORECASTS_BASENAME in new:
                new[CONF_WEATHER_NAME] = config_entry.data[CONF_FORECASTS_BASENAME]

            config_entry.version = 2
            hass.config_entries.async_update_entry(config_entry, data=new)

        _LOGGER.info("Migration to version %s successful", config_entry.version)
```

So that when updating to 1.1.6 or later it copies the current base name to the weather name. I am working on doing that and am just about to do some testing.

**Comment by Makin-Things** [comment]
@glenn20 I have pushed a fix to main. Can you do some testing with it as well. It worked for me and didn't break on upgrading.

**Comment by glenn20** [comment]
Whoops - my bad. I tested for a fresh install and config flow - but not for upgrade. I understand the implications now. I'll test now.

**Comment by glenn20** [comment]
Small fixes required - I'll post a PR after a little more testing.

**Comment by glenn20** [comment]
New PR at #122. 

Thanks Simon for the quick fix for the bug I introduced. PR 122 applies a moinor fix after some testing of fresh installations and upgrades from older versions:

- On my homeassistant, async_migrate_entry() is expected to be a module-level function, not a method of ConfigFlow class.
- Set the fallback weather_name to Home, rather than "home" to respect expected title case.
  - Note: this fallback __should__ no longer be invoked for upgrades of existing BoM integrations or creation of new BoM integrations.

**Comment by Makin-Things** [comment]
Ok that looks good. I don't know how it worked for me then. Even the dev docs say that function should be in __init__.py. I have merged it but haven't done a release quite yet. So you should be able to use HACS to pull main if you want to do some final testing.

On another note, I had a look at trying to figure out how to fix issue #113, but my python skills are a little lacking. I verified it is a problem, but not sure how to fix it. If you would like to have a look that would be awesome.

**Comment by glenn20** [comment]
OK - shall do. Re. 113, it seems there are two options: 

1. Delete the call to `collector.async_update()` from `async_setup_entry()` which would mean replacing `collector.locatiions_data['data']['name']` with `entry.data[WEATHER_NAME]`, OR
2. Trap the ClientConnectorError exception from collector.async_update() and raise ConfigEntryNotReady.

I think option 1 makes the most sense. If we are unable to make a connection to the BoM services that shouldn't stop us from setting up the integration on boot. There will be a one-off impact where the name registered with the DataUpdateCoordinator __may__ change if the user has set a named for their weather entity which is different to the suburb name. I believe that will be innocuous - but will test.

**Comment by Makin-Things** [comment]
@Daneish we have just released 1.1.7 that should fix this issue. Please upgrade and let us know.

**Comment by Daneish** [comment]
Thanks very much for the super quick response and fix. I downgraded to 1.1.5 earlier today and that indeed was a work around, my old entities came back to life. I just updated to 1.1.7 now and all is still working. Great work all!

**Comment by Makin-Things** [comment]
Closing as 1.1.7 fixes.
