### ISSUE TITLE
Possible to include BoM river height data?

### ISSUE THREAD

**Issue by Wholistic** [bremor/bureau_of_meteorology#124]
Hi,

With all the recent flooding, one very useful but inaccessible data point for me would be the river height data presented by the BoM.

This could then be made available for push notifications, and even physical warning alarms in certain conditions.

An example of the dataset here - http://www.bom.gov.au/fwo/IDN60231/IDN60231.058180.tbl.shtml

There was even some python code written to help; but I think the home assistant integration would make this far more useful. 

[Riverheight copy.txt](https://github.com/bremor/bureau_of_meteorology/files/8700364/Riverheight.copy.txt)

**Comment by Makin-Things** [comment]
This is not easy to do. The BoM don't actually publish the data in an easily used format. The link you gave above gives a full html page with the data embedded in it. That would mean have to web scrape it to extract the data (which is frowned upon by the HA devs). Additionally the is no linkage from the forecast/observations location used in the api to any of the river height products.
Also the warnings provided by the api (which include flood warnings) have almost no useful data in them, they link to other html pages that contain the text of the warning, so doing anything programmatically with that would also be near impossible.
There is some work going on to include whatever info the warnings contain, but I doubt it will be very useful.

**Comment by Wholistic** [comment]
Is there a pathway to appeal to the BoM to get this data made available?

It's public data that can help the general public save lives and property, it shouldn't be unavailable.
