### ISSUE TITLE
Where to enter the required information?

### ISSUE THREAD

**Issue by Trev-W** [bremor/bureau_of_meteorology#13]
Ok I installed via HACS as per the instructions, now what? Where do I enter the required information (latitude/longitude)? Where in lovelace does this integration show?

**Comment by bremor** [comment]
# Configuration
1. Goto the `Configuration` -> `Integrations` page.  
2. On the bottom right of the page, click on the Orange `+` sign to add an integration.
3. Search for `Bureau of Meteorology`. (If you don't see it, try refreshing your browser page to reload the cache.)
4. Enter the required information. (Latitude/Longitude)

**Comment by Trev-W** [comment]
Yes I already did steps 1,2 & 3 before  posted this issue – where/how do I do step 4?  Sent from Mail for Windows 10 From: bremorSent: Saturday, 31 October 2020 3:48 PMTo: bremor/bureau_of_meteorologyCc: Trev-W; AuthorSubject: Re: [bremor/bureau_of_meteorology] Where to enter the required information? (#13) ConfigurationGoto the Configuration -> Integrations page.On the bottom right of the page, click on the Orange + sign to add an integration.Search for Bureau of Meteorology. (If you don't see it, try refreshing your browser page to reload the cache.)Enter the required information. (Latitude/Longitude)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. 



	
		
			
				
			
		
		
			
				This email has been checked for viruses by Avast antivirus software.
				www.avast.com

**Comment by Trev-W** [comment]
OK got it – you don’t mean within HACS – you mean the normal HA Integrations page. Cheers Sent from Mail for Windows 10 From: bremorSent: Saturday, 31 October 2020 3:48 PMTo: bremor/bureau_of_meteorologyCc: Trev-W; AuthorSubject: Re: [bremor/bureau_of_meteorology] Where to enter the required information? (#13) ConfigurationGoto the Configuration -> Integrations page.On the bottom right of the page, click on the Orange + sign to add an integration.Search for Bureau of Meteorology. (If you don't see it, try refreshing your browser page to reload the cache.)Enter the required information. (Latitude/Longitude)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. 



	
		
			
				
			
		
		
			
				This email has been checked for viruses by Avast antivirus software.
				www.avast.com

**Comment by bremor** [comment]
I think you figured it out now. I will update the instructions to be more clear. Cheers.

**Comment by Trev-W** [comment]
Cheers, sorry mate yeah once I went to the normal integrations page all
good. Thanks very much.
