### ISSUE TITLE
Statistics Graph Card Configuration - Entity not listed

### ISSUE THREAD

**Issue by barradan** [bremor/bureau_of_meteorology#131]
Hi, I'm trying to add the temperature sensor to a statistics graph card but am running into a problem where I can't select the data source. HA has pointed me to this link: https://www.home-assistant.io/more-info/statistics/

Is it possible it can be configured to track statistics?

![image](https://user-images.githubusercontent.com/34226368/172626737-42808602-b10c-4c01-b287-940b815ce2a9.png)

**Comment by Makin-Things** [comment]
You have posted in the wrong repository. This is the BoM weather integration. Closing.

**Comment by barradan** [comment]
Hi, I'm aware this is the BoM weather integration repo, thats why I posted it here.

I'm trying to use the air temp sensor on a statistics card.

This sensor:

![image](https://user-images.githubusercontent.com/34226368/173846899-65b0d32a-eea1-4d71-affc-7e4b9c71bb7c.png)
