### ISSUE TITLE
Overriding deprecated methods

### ISSUE THREAD

**Issue by tomlut** [bremor/bureau_of_meteorology#132]
After updating to core-2022.7.0b0 the following warning is present:

```
Logger: homeassistant.components.weather
Source: components/weather/__init__.py:308
Integration: Weather (documentation, issues)
First occurred: 19:16:37 (2 occurrences)
Last logged: 19:16:40

custom_components.bureau_of_meteorology.weather::WeatherBase is overriding deprecated methods on an instance of WeatherEntity, this is not valid and will be unsupported from Home Assistant 2023.1. Please report it to the custom component author.
```

Possibly related to this developer blog entry:

https://developers.home-assistant.io/blog/2022/06/27/weather_entity_refactoring/

**Comment by Makin-Things** [comment]
A pre-release (1.1.11b0) to fix this has been published, but it can't be installed on anything less that 2022.7.0 (beta's appear to be considered a lower release). Will test fully once 2022.7.0 is released later this week.

**Comment by tomlut** [comment]
Sorry thought I had closed this.
