### ISSUE TITLE
Adding more sensors

### ISSUE THREAD

**Issue by oneseventhree** [bremor/bureau_of_meteorology#133]
Hi,

I have set up my sensors but only selected a few. Is there a way to select more after I've already installed the integration without adding a second integration?

**Comment by loryanstrant** [comment]
I'd love this too, as I have wind forecast in my hourly sensor but not in my daily sensor (not sure if that's a limitation, or if it's something I can configure - but I can't see how to do it).

**Comment by Makin-Things** [comment]
Just delete the integration and re-add it. You get asked all the questions again. Make sure you use the same name though.

**Comment by oneseventhree** [comment]
> Just delete the integration and re-add it. You get asked all the questions again. Make sure you use the same name though.

Thought as much. I wish there was a way to check off the sensors you want to remove instead of just disabling them in HA or deleting and installing the integration again
