### ISSUE TITLE
Please add support for retrieving 'rain last 24hrs' data

### ISSUE THREAD

**Issue by sparkydave1981** [bremor/bureau_of_meteorology#14]
Previously we had the actual rainfall data since 9am as 'rain today'.  Can this be added as an entity with this new component?

**Comment by DavidFW1960** [comment]
Dupe Dave.. you might want to close this one as well

**Comment by sparkydave1981** [comment]
Yep, GitHub had a freak out when I posted and this wasn't supposed to have gone through
