### ISSUE TITLE
Can't install via HACS on HA 2022.06.7

### ISSUE THREAD

**Issue by tbgoose** [bremor/bureau_of_meteorology#141]
Received the following error when trying to install via HACS. No trouble manually installing latest version (1.1.13).
![image](https://user-images.githubusercontent.com/11631657/177229396-234fb9e1-6721-4056-8d01-7e3b6101ea4e.png)

Home Assistant Core 2022.6.7
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.2

Cheers

**Comment by Makin-Things** [comment]
It's not an error. It is telling you that this release isn't supported until HA 2022.7.0 which will be released on Thursday. 2022.7.0 contains some changes that will result in deprecation messages in the logs. I would recommend installing 1.1.13 on 2022.6 as it will probably not be functional as it relies on the upcoming changes in HA.

**Comment by tbgoose** [comment]
Right, cheers. I tried changing version level to older / main and the error message remained. Which version would you suggest?

**Comment by Makin-Things** [comment]
Stick with 1.1.10 until after you upgrade HA to 2022.7.

**Comment by tbgoose** [comment]
Thanks, the one version I didn't click on in HACS... :0

Thanks will reinstall.
