### ISSUE TITLE
Short text and Extended Text

### ISSUE THREAD

**Issue by oneseventhree** [bremor/bureau_of_meteorology#144]
Hi,

I've started to use this amazing integration to TTS to my alexa devices as I don't trust the Amazon Weather.

The only problem is the Short text or Extended text doesn't flow as well with TTS. I am happy to make a template sensor that changes eg. "Mostly clear. Light winds." to "Mostly clear with light winds." but was wondering if there was a list of all the short and extented text BOM uses or is it forever changing?

Thanks,

**Comment by Makin-Things** [comment]
Nup. It is free form. You occasionally get a shocker when they let the work experience kid write it.

**Comment by oneseventhree** [comment]
> Nup. It is free form. You occasionally get a shocker when they let the work experience kid write it.

I actually laughed out loud haha. Is there anything thats not freeform? Is the short text also free form?

**Comment by Makin-Things** [comment]
All the text is free form, both short and extended. I have seen some shockers, but the NWS in the US is even more special in that special kind of way.
