### ISSUE TITLE
Feels like temp

### ISSUE THREAD

**Issue by oneseventhree** [bremor/bureau_of_meteorology#146]
Hi,

Is there a feels like temp for my weather sensor or is it only on the observation sensor?

**Comment by Makin-Things** [comment]
As long as you selected it as an observation you wanted when setting up the integration it should exist.

There are some weather stations although (mostly within suburbia of the big cities that won't report it as the stations don't have all the sensors required). Feel's like is just a calculation based that uses temperature, humidity and wind speed as inputs. If any of those are missing you can't calculate the value.

**Comment by Makin-Things** [comment]
Closing as I believe the question has been answered.
