### ISSUE TITLE
Can I specify a weather station ID?

### ISSUE THREAD

**Issue by Rolzzz** [bremor/bureau_of_meteorology#148]
hello there, this integration looks amazing, but keeps choosing the closest land station when I'm after a specific station ID to get Wind details... 

Can I force specify a station ID?

**Comment by Makin-Things** [comment]
If you use the lat/lon of the weather station when creating the extra sensors it will use those to find the closest weather station.
You probably only want to select 'observations' so you don't end up with multiple forecast/warning sensors.

**Comment by Rolzzz** [comment]
> If you use the lat/lon of the weather station when creating the extra sensors it will use those to find the closest weather station. You probably only want to select 'observations' so you don't end up with multiple forecast/warning sensors.

Hi Makin, I tried all manner of options before posting... all I can think of is the weather station I want doesn't have temp just wind and this is what could be throwing off the app.

even tried selecting a real suburb that is closer as per BOM's site recognises it, but still chooses Alex Hill station

![image](https://user-images.githubusercontent.com/29428938/182244684-9554c084-7876-4a57-a4f5-7e25f275d170.png)

**Comment by Rolzzz** [comment]
> If you use the lat/lon of the weather station when creating the extra sensors it will use those to find the closest weather station. You probably only want to select 'observations' so you don't end up with multiple forecast/warning sensors.

ok unselecting all looked like it maybe, worked! Thank you!

Now to work out how to just pull out wind data so I can put into my Grafana instance.

**Comment by Makin-Things** [comment]
Something that may also help with this. I just put up a pre-release  (1.1.14b0) that now allows you to reconfigure the integration.
Also the way I set things up as I have 2 BoM weather stations  equidistant from me. I add the integration 3 times. The first one I use my home coordinates and select what I want in forecast and warnings (disable observations). The other 2 I use coordinates close the the weather station (the BoM publish those if you go looking) and then only select observations for those (disable forecast and warnings).
The logic behind this is that forecasts and warnings are calculated by a super-computer based off mathematical models (no need for any instruments on the ground). For observations you need actual instruments that have a real location, the integration just finds the closest one of these to the coordinates entered and uses that.

**Comment by Rolzzz** [comment]
hey @Makin-Things thanks for sticking with me... yeah I'm definitely in need of the observation part, but again... no matter what the location I choose it always wants to pick the one I don't want to use...

for example, I will choose Dunwich (Stradbroke Island, QLD) Say -27.498348, 153.402789 you can see Banana Bank is clearly closer

![image](https://user-images.githubusercontent.com/29428938/182362515-1e50365a-3b7f-4d9e-b3b6-aa7ad159db7d.png)

Here is what I see... new integration setup... punch in lat/long

![image](https://user-images.githubusercontent.com/29428938/182362691-d3533611-b474-4e10-ae00-e3e001b83d4f.png)

it recognises the location

![image](https://user-images.githubusercontent.com/29428938/182362760-64dc68b3-cff1-4c79-8e50-868191add9b1.png)

select observational sensors

![image](https://user-images.githubusercontent.com/29428938/182362960-77366f32-3840-49d1-a0ee-6cab957b8a86.png)

and bam... gives me Redlands (Alex Hills)

![image](https://user-images.githubusercontent.com/29428938/182363053-780fdf94-06d6-4974-ba29-eaa9b310f3e0.png)

**Comment by Makin-Things** [comment]
Unfortunately this looks like a BoM limitation and I doubt there is anything we can do.
The integration uses the same api's as https://weather.bom.gov.au which when you enter your coordinates into the search results in data from Redland. I suspect is because the one you are looking for only provides wind info.

**Comment by Rolzzz** [comment]
I figured this was the case, but had to ask... thank you.
