### ISSUE TITLE
'Rain today' data

### ISSUE THREAD

**Issue by sparkydave1981** [bremor/bureau_of_meteorology#15]
Previously we had the actual rainfall data since 9am as 'rain today'.  Can this be added as an entity with this new component?

**Comment by DavidFW1960** [comment]
It is available in the new component.... are you really not seeing that?

**Comment by sparkydave1981** [comment]
Nope.  I don't have any current conditions at all now that I'm looking into it further.

These are all the entities I have:

sensor.morley_extended_text_0
sensor.morley_extended_text_1
sensor.morley_extended_text_2
sensor.morley_extended_text_3
sensor.morley_extended_text_4
sensor.morley_extended_text_5
sensor.morley_fire_danger_0
sensor.morley_fire_danger_1
sensor.morley_fire_danger_2
sensor.morley_fire_danger_3
sensor.morley_fire_danger_4
sensor.morley_fire_danger_5
sensor.morley_icon_0
sensor.morley_icon_1
sensor.morley_icon_2
sensor.morley_icon_3
sensor.morley_icon_4
sensor.morley_icon_5
sensor.morley_max_0
sensor.morley_max_1
sensor.morley_max_2
sensor.morley_max_3
sensor.morley_max_4
sensor.morley_max_5
sensor.morley_min_0
sensor.morley_min_1
sensor.morley_min_2
sensor.morley_min_3
sensor.morley_min_4
sensor.morley_min_5
sensor.morley_rain_amount_max_0
sensor.morley_rain_amount_max_1
sensor.morley_rain_amount_max_2
sensor.morley_rain_amount_max_3
sensor.morley_rain_amount_max_4
sensor.morley_rain_amount_max_5
sensor.morley_rain_amount_min_0
sensor.morley_rain_amount_min_1
sensor.morley_rain_amount_min_2
sensor.morley_rain_amount_min_3
sensor.morley_rain_amount_min_4
sensor.morley_rain_amount_min_5
sensor.morley_rain_amount_range_0
sensor.morley_rain_amount_range_1
sensor.morley_rain_amount_range_2
sensor.morley_rain_amount_range_3
sensor.morley_rain_amount_range_4
sensor.morley_rain_amount_range_5
sensor.morley_rain_chance_0
sensor.morley_rain_chance_1
sensor.morley_rain_chance_2
sensor.morley_rain_chance_3
sensor.morley_rain_chance_4
sensor.morley_rain_chance_5
sensor.morley_short_text_0
sensor.morley_short_text_1
sensor.morley_short_text_2
sensor.morley_short_text_3
sensor.morley_short_text_4
sensor.morley_short_text_5
sensor.morley_uv_category_0
sensor.morley_uv_category_1
sensor.morley_uv_category_2
sensor.morley_uv_category_3
sensor.morley_uv_category_4
sensor.morley_uv_category_5
sensor.morley_uv_end_time_0
sensor.morley_uv_end_time_1
sensor.morley_uv_end_time_2
sensor.morley_uv_end_time_3
sensor.morley_uv_end_time_4
sensor.morley_uv_end_time_5
sensor.morley_uv_max_index_0
sensor.morley_uv_max_index_1
sensor.morley_uv_max_index_2
sensor.morley_uv_max_index_3
sensor.morley_uv_max_index_4
sensor.morley_uv_max_index_5
sensor.morley_uv_start_time_0
sensor.morley_uv_start_time_1
sensor.morley_uv_start_time_2
sensor.morley_uv_start_time_3
sensor.morley_uv_start_time_4
sensor.morley_uv_start_time_5

**Comment by sparkydave1981** [comment]
Sorry, ignore me.  It turns out that some entities are not listed under 'Morley', but 'Perth'.

**Comment by DavidFW1960** [comment]
Yeah the observations and forecast are in a different suburb. The reason is the observations are based on a specific observation station while the forecast is a computer interpolation model for your exact suburb....
