### ISSUE TITLE
Upgrade Method Documentation

### ISSUE THREAD

**Issue by whatsupskip** [bremor/bureau_of_meteorology#151]
Just wondering what is best way to upgrade this integration. There is nothing in the Readme about it.

**Comment by Makin-Things** [comment]
HACS will offer the upgrade.

**Comment by whatsupskip** [comment]
Thanks.

**Comment by Makin-Things** [comment]
Did you get it sorted? Nothing was added to the doco as upgrading things via HACS is a well known process.

**Comment by whatsupskip** [comment]
Yes, thank you. I thought I looked in that section before asking here.

Thank you again for all your efforts with this project.
