### ISSUE TITLE
initial setup problem and question

### ISSUE THREAD

**Issue by MikeatLorne** [bremor/bureau_of_meteorology#152]
I am new to this....
I've set up the  BOM.weather integration and although it appears to be working, I am getting this error. 
Logger: homeassistant.setup
Source: setup.py:320
First occurred: 07:21:58 (1 occurrences)
Last logged: 07:21:58
Unable to prepare setup for platform bureau_of_meteorology.weather: Platform not found (No module named 'custom_components.bureau_of_meteorology.weather').
I've reinstalled with the same result - any ideas?

Separately, I ended up with 2 "services" - one being my nearest BOM node and the other apparently being my "home".  I tried a few different ways on configuring things on installation but still ended up with both

thanks

**Comment by Djelibeybi** [comment]
Seeing two services is expected if you use the default naming suggested by the integration during configuration, with a service created for each name. One provides the current `weather` entity and forecast for however many days you chose and the other provides current conditions at the chosen weather station.

**Comment by MikeatLorne** [comment]
thanks for the rapid response so confirming it is normal to see 2 devices.  PS - any response to my first question?

**Comment by Djelibeybi** [comment]
That one I'm not sure about. I wrote the services bit, so I knew that answer. :) It's a weird error though. Did you install via HACS or manually?

**Comment by MikeatLorne** [comment]
HACS

**Comment by MikeatLorne** [comment]
I re-installed again and it seems to be working fine - thanks again

**Comment by Makin-Things** [comment]
It could have been some sort of weird caching issue. I haven't seen that error reported before though.
The reason for the 2 different services is that the BoM use computer modelling to create forecasts based on a grid, so you forecasts are pretty much your exact location, while observations are taken at specific locations as measuring instruments are required.
Since it is now working I will close this now.
