### ISSUE TITLE
rain forecast index

### ISSUE THREAD

**Issue by MikeatLorne** [bremor/bureau_of_meteorology#153]
I have set this template up to generate an "index" of the likelihood/quantity of rain in the next 4 days divided by the average of the next 4 days maximum temperatures.  I'll use this to enable/disable my existing irrigation controllers.  The template seems to be working fine but I am not convinced it is generating a number as my automation is not responding as expected as the variable changes during the day, nor can I see a graph when clicking on its icon instead I get a history trace.  I am sure it is something simple for a trained eye but I have tried everything I know (which is not much)! thanks
- name: rain_4_day_forecast_index
    state: >
      {{ ((states.weather.home.attributes["forecast"][0]["precipitation_probability"]|float*
     states.weather.home.attributes["forecast"][0]["precipitation"]|float +
      states.weather.home.attributes["forecast"][1]["precipitation_probability"]|float *
      states.weather.home.attributes["forecast"][1]["precipitation"]|float +
      states.weather.home.attributes["forecast"][2]["precipitation_probability"]|float *
      states.weather.home.attributes["forecast"][2]["precipitation"]|float  +
      states.weather.home.attributes["forecast"][3]["precipitation_probability"]|float*
      states.weather.home.attributes["forecast"][3]["precipitation"]|float)/
      (states.weather.home.attributes["forecast"][0]["temperature"]|float +
      states.weather.home.attributes["forecast"][1]["temperature"]|float +
      states.weather.home.attributes["forecast"][2]["temperature"]|float +
      states.weather.home.attributes["forecast"][3]["temperature"]|float))|float|round(0) }}

**Comment by Makin-Things** [comment]
Sorry, but I don't have the time to help with this issue that isn't really related to the actual integration. You would be better off asking in the HA Community forums.
