### ISSUE TITLE
Fire Danger entities not working

### ISSUE THREAD

**Issue by sabbrowne** [bremor/bureau_of_meteorology#154]
Dear Bremor,
I have been using this HACs integration for several years now. It is generally rock solid. So thanks for the great work.
Over the last month the Fire Danger Index entities are always set to 'unknown'.
ie for my Location
sensor.trafalgar_fire_danger_0
sensor.trafalgar_fire_danger_1
sensor.trafalgar_fire_danger_2
sensor.trafalgar_fire_danger_3
sensor.trafalgar_fire_danger_4
sensor.trafalgar_fire_danger_5
sensor.trafalgar_fire_danger_6
I suspect this maybe because the BOM API has changed their schema for Victoria and possibly other States to align with a National Standard for Fire Danger index. I think they changed from a 5 tier to 4 tier. See 
http://www.bom.gov.au/vic/forecasts/fire-danger-ratings.shtml

Index number range (category)	Fire danger rating
12 to 23	Moderate
24 to 49	High
50 to 99	Extreme
100-plus	Catastrophic

Or of course I may have something else totally wrong.
I have the latest version of the HACS BOM integration installed 1.1.14

**Comment by Makin-Things** [comment]
The new fire danger ratings are a cluster. While the official ratings say there are only 4 levels (Moderate, High, Extreme and Catastrophic) in reality there are 2 additional states that the BoM now use (No Rating and null). Over the cold months the BoM don't bother with fire danger data as the risk is so low (null in the data, but translates to unknown in HA). The seem to use 'No Rating' at times for low fire danger. At the moment your locations has null for the fire danger for every day.
I am not going to make any changes to the integration at this point in time as I suspect the BoM will just change things again when they realise they are confusing everyone.

**Comment by sabbrowne** [comment]
Hi. Thanks for the prompt reply. I thought this may have been the case with no data. Was just making sure you were on top of the changes 😊 Again thanks for the great integration 

shane
