### ISSUE TITLE
Can't install integration

### ISSUE THREAD

**Issue by sampalmer** [bremor/bureau_of_meteorology#157]
Hi, I'm using Home Assistant 9.2, and I'm unable to add this integration. I'm probably missing something obvious, but I've tried following the instructions in the readme, but this integration doesn't appear when I search for it using either Home Assistant's web UI or the public website

**Comment by Makin-Things** [comment]
Sorry, but you didn't provide enough info to provide help. Are you using HACS to install? Show a screen capture of where you can't find it etc.

**Comment by sampalmer** [comment]
My mistake. I spent some more time on it and figured out how HACS works. Now I've got it up and running. So far this integration looks very good!
