### ISSUE TITLE
Not an Issue, Request for information

### ISSUE THREAD

**Issue by wizy69** [bremor/bureau_of_meteorology#158]
Not sure of another way to request this information, so please forgive me in advance. I have loaded the integration correctly in Home Assistant, wanting more information on what the different data elements are, eg ... Extended text 0-7, Danger 0-7, , are these current being 0 and 7 being seven day forcast? Just wanting some clarity

**Comment by Makin-Things** [comment]
Anything with a suffix of _0 is today, _1 is tomorrow and so on.
