### ISSUE TITLE
Extended text truncated

### ISSUE THREAD

**Issue by ronnybugle** [bremor/bureau_of_meteorology#159]
Hi, I hope this is ok to start an issue...

The plugin for HA is brilliant.  However, there is one disappointing thing: Most of the time the Extended Text 1, Extended Text 2 etc fields are truncated with a ... at the end of the field if the field value exceeds a certain length (I presume).  Is that a HA limitation of the sensor field size? or is it being cut-off from within the plugin after data retrieval?  Is there a way to fix it please?
![HA BOM Plugin issue](https://user-images.githubusercontent.com/70496823/205521926-73d48e57-ad98-434b-9864-31fa99d8ffaa.jpg)

**Comment by djferg** [comment]
The full extended text is being correctly received by the integration. It appears to be home assistant that is truncating the sensor state when displaying it. Even templating with {{states.sensor.kenthurst_extended_text_1.state}} was it again truncated.

You can, however, access the full text by accessing the {{states.sensor.kenthurst_extended_text_1.attributes.state}} instead.

![image](https://github.com/bremor/bureau_of_meteorology/assets/125743866/9f37b566-ba93-4edd-86e3-867ee81e9c7e)

**Comment by DavidFW1960** [comment]
There is a 256 character limit for states in HA but no limit for attributes

**Comment by ronnybugle** [comment]
Thank you!!
