### ISSUE TITLE
Continuing issue with "Clear Night" during the day

### ISSUE THREAD

**Issue by atyndall** [bremor/bureau_of_meteorology#163]
I'm experiencing the issue described in #74, in that the current forecast status seems to be timeshifted into the future, indicating that the forecast is "Clear, night", even though it is 3pm currently.

I'm located in Perth which is 3 hours behind the eastern states, so it does smell like some sort of timezone handling issue, as "Clear, night" is the forecast later in the evening.

I've checked the BOM website and app for my weather station, and neither of them are showing "Clear, night" as the current conditions (they're both "Sunny"). Suggests maybe there is something going on in the extension code?

Here are some API outputs:
https://gist.github.com/atyndall/91f81c5fe5311070e48f5fca2bf35137

My dashboard:
<img width="500" alt="Screen Shot 2023-01-08 at 2 54 11 pm" src="https://user-images.githubusercontent.com/1833303/211184341-805b5bdc-6536-4056-9878-5284a7f6548d.png">
<img width="500" alt="Screen Shot 2023-01-08 at 2 54 21 pm" src="https://user-images.githubusercontent.com/1833303/211184338-d53ee0e5-00c5-4dad-9456-3fe3870b45db.png">

BOM Website:
<img width="500" alt="Screen Shot 2023-01-08 at 2 53 09 pm" src="https://user-images.githubusercontent.com/1833303/211184446-5444c1a0-2bd5-4c73-bca6-d158203e886a.png">

BOM App:
<img height="500" alt="Screen Shot 2023-01-08 at 2 53 09 pm" src="https://user-images.githubusercontent.com/1833303/211184473-828c7c12-0bf8-4a17-b3ac-254281751b26.PNG">

**Comment by atyndall** [comment]
Captured some more information from another occurrence. Night seems to start around 2pm?

<img width="239" alt="Screen Shot 2023-01-15 at 2 12 25 pm" src="https://user-images.githubusercontent.com/1833303/212525834-9be0aac1-8075-4a2e-8a27-31171a28efe6.png">
<img width="1673" alt="Screen Shot 2023-01-15 at 2 12 17 pm" src="https://user-images.githubusercontent.com/1833303/212525836-9a626759-31c4-467e-8222-a8e41c0655d8.png">

**Comment by flybrys** [comment]
I'm getting the opposite, where it says sunny during the night

**Comment by omad** [comment]
@atyndall 
That's really curious. Is it still happening? 
From your last screenshot it looks like UTC time is being used instead.

This component converts the UTC times from the BoM API into the timezone also available from the BoM API for your configured location (available from e.g.  https://api.weather.bom.gov.au/v1/locations/qd66j8/).

Things to check:
- What timezone do you have set in Home Assistant (Settings -> System -> General).
- Are the other dates within Home Assistant that are wrong?
- Are there other dates from this Integration that are wrong? (I can see that UV warning times are converted... but it's the wrong time of year for that to be apparent).
- How is Home Assistant installed? (HA Operating System/Container/Core) (This could be caused by an environment issue, if the TimeZone database is missing or faulty)

**Comment by atyndall** [comment]
Hi @omad,

It's unfortunately difficult to determine if it's still happening with the forecast, as with the history I have available currently, it has been consistently raining, so there has been no "Clear, night" forecast for a while.

I have observed some other interesting strangeness. Around the day boundaries there appear to be "unknown" data gaps that are of inconsistent timing and length. I wonder if that is related.
<img width="1338" alt="Screenshot 2023-06-08 at 2 32 22 pm" src="https://github.com/bremor/bureau_of_meteorology/assets/1833303/3b4e48eb-e087-4ffc-9ed5-91806adfc376">
<img width="250" alt="Screenshot 2023-06-08 at 2 32 27 pm" src="https://github.com/bremor/bureau_of_meteorology/assets/1833303/7bc33889-3dc0-49a7-8370-cbcc504994a2"><img width="236" alt="Screenshot 2023-06-08 at 2 32 32 pm" src="https://github.com/bremor/bureau_of_meteorology/assets/1833303/82921b27-b45e-4249-89c6-e2018d887185"><img width="257" alt="Screenshot 2023-06-08 at 2 32 36 pm" src="https://github.com/bremor/bureau_of_meteorology/assets/1833303/e712afaa-7eb8-495a-ace9-69c67c0d3517">
<img width="350" alt="Screenshot 2023-06-08 at 2 34 26 pm" src="https://github.com/bremor/bureau_of_meteorology/assets/1833303/54559f3d-17ac-4828-a700-f18743747fa6"><img width="350" alt="Screenshot 2023-06-08 at 2 34 42 pm" src="https://github.com/bremor/bureau_of_meteorology/assets/1833303/90428b88-25fb-4173-b910-20f35a5d9b00">

>What timezone do you have set in Home Assistant (Settings -> System -> General).
<img width="200" alt="Screenshot 2023-06-08 at 2 27 48 pm" src="https://github.com/bremor/bureau_of_meteorology/assets/1833303/0ac02c29-d0bf-4460-898f-1fb2920de76a">

Seems to be correctly set to my TZ

>Are the other dates within Home Assistant that are wrong?

Not that I've observed. All my other sensor logging seems to be aligned correctly with my timezone.

>Are there other dates from this Integration that are wrong? (I can see that UV warning times are converted... but it's the wrong time of year for that to be apparent).
<img width="200" alt="Screenshot 2023-06-08 at 2 33 56 pm" src="https://github.com/bremor/bureau_of_meteorology/assets/1833303/916ea9dd-d6be-421c-b94e-aac62d1827b1">

I did some other spot checking, and from what I can tell at least sunset time is accurate.

>How is Home Assistant installed? (HA Operating System/Container/Core) (This could be caused by an environment issue, if the TimeZone database is missing or faulty)

It was a while ago I believe it's Home Assistant Core installed on a Debian VM;
```
atyndall@homeassistant:~$ uname -a
Linux homeassistant 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux
```

**Comment by omad** [comment]
Hi @brywithawhy

> I'm getting the opposite, where it says sunny during the night

That could be the same issue I'm getting, see https://github.com/bremor/bureau_of_meteorology/issues/177 for details.

**Comment by Makin-Things** [comment]
This is a BoM problem. The integration only makes available the data they publish.

**Comment by atyndall** [comment]
@Makin-Things I don't think this is a particularly reasonable response.

At all times that I have detailed, the BOM website and app (which I understand use the same API that the integration uses) have shown the accurate information. This suggests that the bug lies in this extension's interpretation of BoM's API, rather than some defect in the data they publish.

Otherwise how could the BOM website and app show the correct "Sunny" forecast while this extension shows something else?

**Comment by Makin-Things** [comment]
Firstly the BoM website doesn't use the same api, it is only used by the mobile app. The BoM do not document the api since they consider it to be a private api that nothing other than the mobile app is permitted to use (we ignore that and reverse engineered pretty much everything).
If you feel like spending time and figuring it out please do and submit a PR. Unfortunately none of the major contributors have the time to commit.
