### ISSUE TITLE
Enable support for long-term statistics

### ISSUE THREAD

**Issue by corneels** [bremor/bureau_of_meteorology#166]
https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

> Integrations need to configure their entities correctly so Home Assistant knows that we need to track statistics for it and how.

> Home Assistant has support for storing sensors as long-term statistics if the entity has the right properties. To opt-in for statistics, the sensor must have state_class set to one of the valid state classes: measurement, total or total_increasing. For certain device classes, the unit of the statistics is normalized to for example make it possible to plot several sensors in a single graph.

When I try to make a card type 'statistics-graph', I get the following error in the UI: No statistics found.

**Comment by whatsupskip** [comment]
Have you found a solution to this problem?

**Comment by corneels** [comment]
No

**Comment by Makin-Things** [comment]
The integration provides the current data. Long term stats need to be handled by HA itself or use node red/grafana to collect/display.
