### ISSUE TITLE
Undocumented API being retired?

### ISSUE THREAD

**Issue by tomlut** [bremor/bureau_of_meteorology#170]
"This grabs data from an undocumented API that is used to provide data to https://weather.bom.gov.au/"

That page now has the following banner:

"This page will be retired on 14 March 2023
For forecasts, observations, radar and warnings visit [bom.gov.au](http://www.bom.gov.au/) or download the [BOM Weather app](http://www.bom.gov.au/app)."

It is not clear if it is just the web page that is being retired or the API too.

**Comment by bremor** [comment]
I’m thinking it might be time to get my hands dirty again, haha. I’m going to have a crack at sniffing data coming into the BoM app to see where it pulls it’s data from.

**Comment by Makin-Things** [comment]
The BoM app uses the same api. To sniff it you have to have a rooted android device so you can mitm the https traffic.

**Comment by bremor** [comment]
You are right, the BoM app is using the same API which is nice. I am able to MITM using Charles Proxy to see decrypted https traffic, much easier than fiddling around with a rooted device :)

**Comment by tomlut** [comment]
Good news!

thanks for clearing that up.

**Comment by Makin-Things** [comment]
> You are right, the BoM app is using the same API which is nice. I am able to MITM using Charles Proxy to see decrypted https traffic, much easier than fiddling around with a rooted device :)

@bremor Are you able to see the url's they are using for the radar on the mobile app? They changed those to be different from the weather.bom.gov.au website, but I have not had time to do a mitm on it to see what's changed. I suspect this decommissioning will break my radar plugin.
