### ISSUE TITLE
Unable to Install on Integrations Page

### ISSUE THREAD

**Issue by cloudbr34k84** [bremor/bureau_of_meteorology#171]
I noticed for some reason this HACS add on was taking forever to finish starting so i uninstalled it.

Now when i go to try and install it after i have downloaded in HACS, it just sits on this page??

Logs dont dont show anything

![image](https://user-images.githubusercontent.com/58960644/219981977-a08ee513-d644-4658-ae08-730e7f9cc232.png)

**Comment by Steve-gnome** [comment]
dito

**Comment by Makin-Things** [comment]
Stale.
