### ISSUE TITLE
What is the sensor.location_temp_min_0 parameter?

### ISSUE THREAD

**Issue by whatsupskip** [bremor/bureau_of_meteorology#172]
Is there a list of what all the parameters are?
I looked and couldn't find it.

Just wondering what sensor.location_temp_min_0 is?
I am specifically looking for today's min/max temperatures, and may be yesterday's.

Thanks again for all your work on this project.

**Comment by cloudbr34k84** [comment]
it appears this integration has gone stale according to HACS

**Comment by DavidFW1960** [comment]
> sensor.location_temp_min_0

forecast minimum for today. It may show as N/A at some point during the day as BOM removes them when they are 'past'

**Comment by DavidFW1960** [comment]
> it appears this integration has gone stale according to HACS

not sure why. Last update was October.

**Comment by whatsupskip** [comment]
Thank you.

Yes, October last year isn't that long ago.
