### ISSUE TITLE
Cannot connect to host api

### ISSUE THREAD

**Issue by Venj-ADL** [bremor/bureau_of_meteorology#173]
Just in the last couple of days the BoM Radar Card on my Lovelace dash stopped showing any rain data. 

Today I noticed in my logs "Error requesting bureau_of_meteorology data: Cannot connect to host api.weather.bom.gov.au:443 ssl:default [Try again]". The same thing has happened on my friends HA install and neither of us have changed anything in our setups.

<img width="822" alt="Screen Shot 2023-03-22 at 4 18 40 am" src="https://user-images.githubusercontent.com/76688057/226697547-9fa2c26d-9890-4af2-8b3c-63f4217d58eb.png">

**Comment by roly151** [comment]
BOM retired the api that was providing rain radar tiles. They have moved providers to Mapbox. I would say this is the issue.

**Comment by Makin-Things** [comment]
This is not something this integration provides.  The BoM changed the radar data sources. You can use the rainviewer data source on the card though until a new version is written.  See this
https://github.com/Makin-Things/bom-radar-card/issues/32
