### ISSUE TITLE
Hourly Forecast showing Sunny at Night

### ISSUE THREAD

**Issue by omad** [bremor/bureau_of_meteorology#177]
I installed a new widget, and noticed that the hourly forecast thinks the sun shines all through the night. (It goes down about 5:30pm here in Canberra at the moment)
![image](https://github.com/bremor/bureau_of_meteorology/assets/108979/85a6b193-3e77-4259-9391-6fb539ccd1a7)

I can see why from looking at the responses from the BoM API, which includes an `is_night` flag set to true, alongside the `icon_descriptor` saying that it's `mostly_sunny`.

https://github.com/bremor/bureau_of_meteorology/blob/f786f41f77dfd6f93054db8f09bbe34c31052b3a/api%20doc/API.md?plain=1#L685-L689

I'm happy to work up a PR to fix this, by updating the code around 
https://github.com/bremor/bureau_of_meteorology/blob/f786f41f77dfd6f93054db8f09bbe34c31052b3a/custom_components/bureau_of_meteorology/weather.py#L203 to do a more advanced mapping that also takes into account the `is_night` flag.

I think the only cases this applies for are `sunny` and `mostly_sunny`.
https://github.com/bremor/bureau_of_meteorology/blob/f786f41f77dfd6f93054db8f09bbe34c31052b3a/custom_components/bureau_of_meteorology/const.py#L40-L68

**Comment by mjrit** [comment]
I think the problem here might be at BOM's end, the value of that Hourly field for Sydney as been mostly just "Fog" for the last few days and it has not been foggy.
But the "short_text_0" field is updated regularly during the day with more relevant data - for Sydney it's been "Smokey" or "Sunny" during the day and "Clear" at night - maybe that's a better choice for the weather card?

**Comment by bromX** [comment]
I can confirm I am also seeing this.
2:30 in the afternoon super sunny . "clear, night"

![image](https://github.com/bremor/bureau_of_meteorology/assets/58619184/7b28110b-1ffc-42d0-8852-e21188eca548)

**Comment by Makin-Things** [comment]
The integration can only use the data as provided by the BoM.
