### ISSUE TITLE
Hourly forecast card not showing times

### ISSUE THREAD

**Issue by nixmaster2000** [bremor/bureau_of_meteorology#181]
With the frontend update that came with HA 2023.08, the Weather Forecast card when choosing the hourly forecast entity now shows the day of the week where it previously showed the hour. So instead of 8am, 9am, 10am, 11am, 12pm etc, we just get Fri, Fri, Fri, Fri.

Not sure if this is something that can be fixed in the integration or if this is provided by the frontend?

![image](https://github.com/bremor/bureau_of_meteorology/assets/86043088/70d13d35-06c4-438d-bec4-a8a6312e26a0)

**Comment by tramperb** [comment]
Same issue here.  I removed the integration (which has been loaded manually 6 months ago) and relaoded via HACS but result was the same as @nixmaster2000 

The hourly entity has all the attributes correctly (developer tools, states) but just not showing on the weather card.

**Comment by GwynHannay** [comment]
Also having this issue. Don't know how long for, only noticed it this morning. I've tried reloading the config, but same as the others.

**Comment by DavidFW1960** [comment]
There is no weather card for this integration. Contact the dev if it's a custom card or log an issue for HA core if it's a core card.

**Comment by tramperb** [comment]
It would appear to be an issue with the integration, not card(s).

The core Weather Forecast card was showing all the appropriate data prior to 2023.8  After the core update, it's not.  However, another weather integration (Met.no) is showing the correct data.

**Comment by DavidFW1960** [comment]
You said

> The hourly entity has all the attributes correctly (developer tools, states) but just not showing on the weather card.

This means the integration is ok

**Comment by tramperb** [comment]
Yeah, fair point but equally, another integration _does_ show the data correctly - which, to me, indicated that integration & the card (Weather Forecast) are OK.
For clarity, here is a screenshot of the two cards.  First is using Met.no (windy) integration with 5-day forecast & hourly forecast - working correctly.  2nd is Bureau of Meterology integration with 5-day & hourly - the hourly pane isn't showing data correctly (although the 5-day is working correctly). 

![cards](https://github.com/bremor/bureau_of_meteorology/assets/85221759/3d129f63-187d-4107-b3d7-551f31c12f96)

What I meant by devTools/states was showing the data correctly is seen here ;
![hourly-data](https://github.com/bremor/bureau_of_meteorology/assets/85221759/e6d0fbee-474d-40fe-bb98-c77e6acb11c1)

Data is readable but the integration isn't reading it correctly.  It did prior to the 2023.8 update so I conclude that the integration was doing something non-standard that is now causing an issue (although happy to admit I don't fully understand what's occurring in the background :).

(edited to update 2nd pic with additional data)

**Comment by DavidFW1960** [comment]
The intergation id providing the data you see in dev-tools. The intergration reads the data from BOM and pases it to HA. Therefore if HA is displaying the data correctly in dev-tools, it can only be getting it from the integration/BOM

**Comment by tramperb** [comment]
Yeah, the BoM integration is pulling the data & HA is receiving it.  But all that data is in one entity's attributes, not individual entities.  HA can read the one entity & display the attributes but can the card pull out the correct data from the attribute string?

If it's not the BoM integration with the issue, how is it that the Weather Forecast card still works with the Met.no integration ?

I've no idea if it's relevant but the attribute string from Met.no has a few additional values in the initial (current wx) part & fewer values in the hourly parts ;
![Met-no](https://github.com/bremor/bureau_of_meteorology/assets/85221759/1b3e4502-582b-4830-bf3e-d34d1628f04d)

**Comment by DavidFW1960** [comment]
Well it depends on what the card is looking for. Is there any difference in the data the integration is providing now as opposed to before 2023.8? I'd doubt it.

**Comment by tramperb** [comment]
No, the data the integration is supplying is the same, certainly. 
Since it's only the core that's changed (& the core can't be faulty :), it suggests to me that either the card or the integration has the issue.  Since the card works with other integration(s), it's OK so that leaves the BoM integration.  My uninformed gut feeling is that there is a typo/bug in the integration that hasn't been relevant until this core update.

Anyway, if it's a core issue, I don't understand enough to log it.

Thanks for the input.

**Comment by 0xadam** [comment]
It's a HA frontend issue. See https://github.com/home-assistant/frontend/issues/17472

Will be fixed with the next release with a frontend bump (hopefully soon!)

**Comment by DavidFW1960** [comment]
it for sure was never an integration issue

**Comment by nixmaster2000** [comment]
That seems pretty conclusive. Will be glad to have it fixed, even the wife has been commenting!
