### ISSUE TITLE
Integration won't load - Can't config location.

### ISSUE THREAD

**Issue by Steve2017** [bremor/bureau_of_meteorology#183]
The BOM integration just suddenly stopped loading, despite multiple reloads and restarts.

When I try to configure it tells me the Lat/Lon is unsupported so I can't even get to a debug file.:
![Screenshot 2023-08-16 152810](https://github.com/bremor/bureau_of_meteorology/assets/23732366/a2b17c93-a1ec-4964-94d2-87d652a12d80)

This is the same location I have been using for a couple of years now.
I have tried redownloading the file, without success.

Home Assistant 2023.8.2
Supervisor 2023.08.1
Operating System 10.4
Frontend 20230802.0 - latest

**Comment by bremor** [comment]
I'm not sure why it would stop working suddenly but try changing your location to somewhere a little bit more inland and see what happens. BoM might be rounding your location into the water, which will cause it to fail.

**Comment by dh0llyw00d** [comment]
I am getting the same error / issue.

**Comment by thomsy81** [comment]
Also getting the same issue

**Comment by Crossy2001** [comment]
Getting the same error here too. Changing the long/lat doesn’t seem to have an effect. 

Changing the value just resets to the old value when hitting submit. Only change seems to come from modifying the location pin within the home assistant settings

**Comment by cloudbr34k84** [comment]
just got the error as well. Tried the above method but either i didnt do it correctly or it didnt do anything

**Comment by rark-ha** [comment]
I'd only just upgraded to 2023.08.03 (from 2023.06.02) an hour ago so I thought it was something to do with the version change on my end? It was working in 2023.03.02 up until then.

Have others restarted in the last few hours or did it come up without a restart?

**Comment by DavidFW1960** [comment]
> I'm not sure why it would stop working suddenly but try changing your location to somewhere a little bit more inland and see what happens. BoM might be rounding your location into the water, which will cause it to fail.

It's killed already configured setupas well

**Comment by cloudbr34k84** [comment]
> I'd only just upgraded to 2023.08.03 (from 2023.06.02) an hour ago so I thought it was something to do with the version change on my end? It was working in 2023.03.02 up until then.
> 
> Have others restarted in the last few hours or did it come up without a restart?

happened after restart for me

**Comment by Crossy2001** [comment]
> I'd only just upgraded to 2023.08.03 (from 2023.06.02) an hour ago so I thought it was something to do with the version change on my end? It was working in 2023.03.02 up until then.
> 
> Have others restarted in the last few hours or did it come up without a restart?

Mine was working on 2023.08.02 up until this morning, no restart, entities all just showing unavailable, tried to reload, and then got the invalid error

**Comment by craigmate** [comment]
I just noticed on my interface that it was showing Unavailable for any temperature/wind direction.  So I reloaded the config, and it failed.  So I removed it, and now get the lat/lon error as in the first post

**Comment by mcvicthor** [comment]
getting the same issue after a restart one hour ago

**Comment by xsaMNJfkltrwq5r3** [comment]
Same issue for me had a working integration, then everything associated with this particular one has failed.  No update or anything occurred to cause this.

**Comment by starryalley** [comment]
The error on mine is:

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/bureau_of_meteorology/PyBoM/collector.py:87
Integration: Bureau of Meteorology (documentation, issues)
First occurred: 5:01:23 PM (1 occurrences)
Last logged: 5:01:23 PM

Error setting up entry Croydon South for bureau_of_meteorology
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bureau_of_meteorology/__init__.py", line 70, in async_setup_entry
    await collector.async_update()
  File "/config/custom_components/bureau_of_meteorology/PyBoM/collector.py", line 87, in async_update
    self.locations_data = await resp.json()
                          ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://api.weather.bom.gov.au/v1/locations/[my location code]')
```

So this is the return of that URL at `https://api.weather.bom.gov.au/v1/locations/[my location code]` 

```
"copyright":"This Application Programming Interface (API) is owned by the Bureau of Meteorology (Bureau). You must not use, copy or share it. Please contact us for more information on ways in which you can access our data. Follow this link http://www.bom.gov.au/inside/contacts.shtml to view our contact details."
```

Doesn't look good? 

[edited: the above is fine]

Maybe we need to pass `content_type=None` in `await resp.json()` in  line 87, in async_update?

**Comment by DavidFW1960** [comment]
It's BOM changed something. Nothing to do with HA version. The weather entity is working still BTW. Only started about 4hrs ago

**Comment by xsaMNJfkltrwq5r3** [comment]
> It's BOM changed something. Nothing to do with HA version. The weather entity is working still BTW. Only started about 4hrs ago

I thought the same, but when I restarted my integration it failed as well.  I assume that because the weather part updates less frequently it was only a matter of time before it would have also failed?

**Comment by DavidFW1960** [comment]
Could be

**Comment by thatguyinoz** [comment]
My quick tests seem to show the api is still working:
`https://api.weather.bom.gov.au/v1/locations/qd66vd`

resp:
`{"metadata":{"response_timestamp":"2023-08-16T08:02:09Z","copyright":"This Application Programming Interface (API) is owned by the Bureau of Meteorology (Bureau). You must not use, copy or share it. Please contact us for more information on ways in which you can access our data. Follow this link http://www.bom.gov.au/inside/contacts.shtml to view our contact details."},"data":{"geohash":"qd66vd","timezone":"Australia/Perth","latitude":-31.84661865234375,"longitude":115.9112548828125,"marine_area_id":null,"tidal_point":null,"has_wave":false,"id":"Ballajura-qd66vd","name":"Ballajura","state":"WA"}}`


`https://api.weather.bom.gov.au/v1/locations/qd66vd/observations`
resp:
`{"metadata":{"response_timestamp":"2023-08-16T08:05:17Z","issue_time":"2023-08-16T08:01:01Z","observation_time":"2023-08-16T08:00:00Z","copyright":"This Application Programming Interface (API) is owned by the Bureau of Meteorology (Bureau). You must not use, copy or share it. Please contact us for more information on ways in which you can access our data. Follow this link http://www.bom.gov.au/inside/contacts.shtml to view our contact details."},"data":{"temp":15,"temp_feels_like":10.5,"wind":{"speed_kilometre":17,"speed_knot":9,"direction":"SW"},"gust":{"speed_kilometre":30,"speed_knot":16},"max_gust":{"speed_kilometre":43,"speed_knot":23,"time":"2023-08-15T20:59:00Z"},"max_temp":{"time":"2023-08-16T06:23:00Z","value":16.1},"min_temp":{"time":"2023-08-15T19:47:00Z","value":10},"rain_since_9am":0,"humidity":48,"station":{"bom_id":"009225","name":"Perth","distance":8832}}}`
but im just a guy using the module, no skills at sorting out code, to match any changes that might have occurred on the BoM end of things.

**Comment by thatguyinoz** [comment]
and further more, the error says `Attempt to decode JSON with unexpected mimetype: text/html` but should'nt the mimetype of the data ne application/json, or even text/plain? maybe BoM are just having a glitch..

**Comment by callifo** [comment]
Mine looks like it died at 13:36 SA time, hasn't had a single successful scrape since then.

**Comment by craigmate** [comment]
I am hoping it is just a glitch with the BOM, the fact that the error says Unsupported Lat/Lon might mean it something on their side., but who knows.  Super annoying, this is a great weather component, which I use for a lot of automations. 
If the BOM has killed it, what do people recommend.

**Comment by ebswift** [comment]
I've got the same issue as reported above with the unexpected mimetype in the logs.

**Comment by jasonpstokes** [comment]
Same issue. Essentially "This API is owned by the Bureau, you must not use it" - have they blocked access to their API now, or perhaps one of their devs pushed the wrong button!?

@thatguyinoz / everyone: if posting the api response, best redact your latitude and longitude to not give away the (likely) location of your home.

**Comment by DavidFW1960** [comment]
> the BOM has killed it, what do people recommend.

I recommend WAITING till Brendon or Simon comments

**Comment by bremor** [comment]
BOM is returning a 403 Forbidden error when the data is polled using the aiohttp library. There should be a way around this.

**Comment by Makin-Things** [comment]
@bremor I will not be able to look at it until the weekend at the earliest. I suspect it is possibly related to request headers, but not sure which one.

**Comment by Tmbao** [comment]
This is what it's getting
```python
>>> resp
<ClientResponse(https://api.weather.bom.gov.au/v1/locations/r3gqyr) [403 Forbidden]>
<CIMultiDictProxy('Server': 'AkamaiGHost', 'Mime-Version': '1.0', 'Content-Type': 'text/html', 'Content-Length': '307', 'Expires': 'Wed, 16 Aug 2023 12:12:06 GMT', 'Date': 'Wed, 16 Aug 2023 12:12:06 GMT', 'Connection': 'close', 'Strict-Transport-Security': 'max-age=31536000 ; includeSubDomains')>
```

From a quick look there is a CDN that's stopping scrapers from fetching the api

**Comment by bremor** [comment]
Setting the User-Agent request header to something valid seems to fix it, but I will leave the release to @Makin-Things 

@Tmbao is right, seems like they have enabled some anti-scraping feature.

**Comment by Tmbao** [comment]
Thanks for the hint, got it to work temporarily for now. I'm surprised that their anti-scraping is quite basic and unsure how long this will be working. Maybe we'll need to contact BOM to continue to use it 🤔 

In the mean time, updated /config/custom_components/bureau_of_meteorology/PyBoM/collector.py to 👇 (basically adding `user-agent`).
```python
"""BOM data 'collector' that downloads the observation data."""
import aiohttp
import asyncio
import datetime
import logging

from homeassistant.util import Throttle

from .const import (
    MAP_MDI_ICON, MAP_UV, URL_BASE, URL_DAILY,
    URL_HOURLY, URL_OBSERVATIONS, URL_WARNINGS
)
from .helpers import (
    flatten_dict, geohash_encode,
)

_LOGGER = logging.getLogger(__name__)
HEADERS = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36'}

def _build_client_session():
    return aiohttp.ClientSession(headers=HEADERS)

class Collector:
    """Collector for PyBoM."""

    def __init__(self, latitude, longitude):
        """Init collector."""
        self.locations_data = None
        self.observations_data = None
        self.daily_forecasts_data = None
        self.hourly_forecasts_data = None
        self.warnings_data = None
        self.geohash7 = geohash_encode(latitude, longitude)
        self.geohash6 = self.geohash7[:6]

    async def get_locations_data(self):
        """Get JSON location name from BOM API endpoint."""
        async with _build_client_session() as session:
            response = await session.get(URL_BASE + self.geohash7)

        if response is not None and response.status == 200:
            self.locations_data = await response.json()

    async def format_daily_forecast_data(self):
        """Format forecast data."""
        days = len(self.daily_forecasts_data["data"])
        for day in range(0, days):

            d = self.daily_forecasts_data["data"][day]

            d["mdi_icon"] = MAP_MDI_ICON[d["icon_descriptor"]]

            flatten_dict(["amount"], d["rain"])
            flatten_dict(["rain", "uv", "astronomical"], d)

            if day == 0:
                flatten_dict(["now"], d)

            # If rain amount max is None, set as rain amount min
            if d["rain_amount_max"] is None:
                d["rain_amount_max"] = d["rain_amount_min"]
                d["rain_amount_range"] = d["rain_amount_min"]
            else:
                d["rain_amount_range"] = f"{d['rain_amount_min']}–{d['rain_amount_max']}"

    async def format_hourly_forecast_data(self):
        """Format forecast data."""
        hours = len(self.hourly_forecasts_data["data"])
        for hour in range(0, hours):

            d = self.hourly_forecasts_data["data"][hour]

            d["mdi_icon"] = MAP_MDI_ICON[d["icon_descriptor"]]

            flatten_dict(["amount"], d["rain"])
            flatten_dict(["rain", "wind"], d)

            # If rain amount max is None, set as rain amount min
            if d["rain_amount_max"] is None:
                d["rain_amount_max"] = d["rain_amount_min"]
                d["rain_amount_range"] = d["rain_amount_min"]
            else:
                d["rain_amount_range"] = f"{d['rain_amount_min']} to {d['rain_amount_max']}"

    @Throttle(datetime.timedelta(minutes=5))
    async def async_update(self):
        """Refresh the data on the collector object."""
        async with _build_client_session() as session:
            if self.locations_data is None:
                async with session.get(URL_BASE + self.geohash7) as resp:
                    self.locations_data = await resp.json()

            async with session.get(URL_BASE + self.geohash6 + URL_OBSERVATIONS) as resp:
                self.observations_data = await resp.json()
                if self.observations_data["data"]["wind"] is not None:
                    flatten_dict(["wind"], self.observations_data["data"])
                else:
                    self.observations_data["data"]["wind_direction"] = "unavailable"
                    self.observations_data["data"]["wind_speed_kilometre"] = "unavailable"
                    self.observations_data["data"]["wind_speed_knot"] = "unavailable"
                if self.observations_data["data"]["gust"] is not None:
                    flatten_dict(["gust"], self.observations_data["data"])
                else:
                    self.observations_data["data"]["gust_speed_kilometre"] = "unavailable"
                    self.observations_data["data"]["gust_speed_knot"] = "unavailable"

            async with session.get(URL_BASE + self.geohash6 + URL_DAILY) as resp:
                self.daily_forecasts_data = await resp.json()
                await self.format_daily_forecast_data()

            async with session.get(URL_BASE + self.geohash6 + URL_HOURLY) as resp:
                self.hourly_forecasts_data = await resp.json()
                await self.format_hourly_forecast_data()

            async with session.get(URL_BASE + self.geohash6 + URL_WARNINGS) as resp:
                self.warnings_data = await resp.json()

```

**Comment by tomlut** [comment]
@Tmbao Would you like to submit that as a PR so that Makin Things just has to merge it for release?

He's a bit busy with work ATM.

**Comment by Makin-Things** [comment]
I have a fix incoming.

On 16/08/2023 10:36:30 PM, tomlut ***@***.***> wrote:
@Tmbao [https://github.com/Tmbao] Would you like to submit that as a PR so that Makin Things just has to merge it for release?
He's a bit busy with work ATM.

**Comment by Makin-Things** [comment]
1.1.20 has been released on HACS to address this issue.
I don't believe it was a deliberate action by the BOM but most likely just a library update that imposed a new requirement.
Please report any ongoing issues if it doesn't fix it for you.

**Comment by Makin-Things** [comment]
Duplicate of #182
