### ISSUE TITLE
Stopped working, “Unsupported Lat/Lon”

### ISSUE THREAD

**Issue by borodaaaaa** [bremor/bureau_of_meteorology#184]
Stopped working. All entities are unavailable. If i try to set it up again it say 

“Unsupported Lat/Lon“

not sure  if that coincidence but at about the same time updated HA to 2023.8.2

![IMG_9610](https://github.com/bremor/bureau_of_meteorology/assets/110703905/fbf9cb90-d7e8-4483-85c0-c8dbc8f30363)

Below is the log: 

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/bureau_of_meteorology/PyBoM/collector.py:87
Integration: Bureau of Meteorology (documentation, issues) 
First occurred: August 16, 2023 at 16:31:36 (7 occurrences) 
Last logged: 09:24:59

Error setting up entry Redcliffe for bureau_of_meteorology
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bureau_of_meteorology/__init__.py", line 70, in async_setup_entry
    await collector.async_update()
  File "/config/custom_components/bureau_of_meteorology/PyBoM/collector.py", line 87, in async_update
    self.locations_data = await resp.json()
                          ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://api.weather.bom.gov.au/v1/locations/r7hv5f')

**Comment by DavidFW1960** [comment]
This has already been fixed. Update to latest version

**Comment by borodaaaaa** [comment]
By some reason HACS did not show update available until I re-download  my current version .19.


 updated to .21 and it is all good now. 
 
Awesome mate. Thank you for your work it is great app that keeps my garden irrigated  based on the rain since 9am sensor!

**Comment by borodaaaaa** [comment]
Fix in by updating to .21
