### ISSUE TITLE
Unsupported Lat/Lon warning

### ISSUE THREAD

**Issue by DonStone2188** [bremor/bureau_of_meteorology#185]
Hi folks,

Suddenly started to receive an ‘unsupported Lat/Lon’ warning. 

Integration worked before without any major issues. Tried other Lat/Lon, reload or re-configure without luck.

Any ideas?

Cheers,
Oli

**Comment by Makin-Things** [comment]
Update.

**Comment by DonStone2188** [comment]
Omg. I missed that update. Thanks!
