### ISSUE TITLE
Can't install update

### ISSUE THREAD

**Issue by beastien** [bremor/bureau_of_meteorology#188]
I'm trying to update from 1.1.19 to 1.1.21 and it sits on installing update indefinitely and never installs.

**Comment by beastien** [comment]
Getting this error in HA log.

This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/bureau_of_meteorology/__init__.py:32
Integration: Bureau of Meteorology (documentation, issues)
First occurred: 6:28:02 PM (1 occurrences)
Last logged: 6:28:02 PM

Setup failed for custom integration bureau_of_meteorology: Unable to import component: No module named 'custom_components.bureau_of_meteorology.PyBoM.collector'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/bureau_of_meteorology/__init__.py", line 32, in <module>
    from .PyBoM.collector import Collector
ModuleNotFoundError: No module named 'custom_components.bureau_of_meteorology.PyBoM.collector'

**Comment by DavidFW1960** [comment]
Try manually updating. You have to update to fix this

**Comment by beastien** [comment]
Is it normal for it to say there is still an update available after manually updating?

**Comment by DavidFW1960** [comment]
No but it seems your HACS is broken

**Comment by beastien** [comment]
Any idea how I could fix it?

**Comment by beastien** [comment]
It couldn't update because HA couldn't contact the Github server.  Fixed it by disabling IPV6 in HA network settings.

**Comment by DavidFW1960** [comment]
I only have HA connected to IPv6 so it's not IPv6 itself causing an issue

**Comment by Steve2017** [comment]
I have v1.1.20 installed. When I try to update to v1.1.21, nothing changes. 

I have deleted the integration in both Integrations and HACS and reinstalled - selecting v1.1.21, but it still just loads v1.1.20. The manifest.json says it is v1.1.21, but on the HACS integration page it is still v20 and showing that v21 is available.


Also on on the HA warning about a deprecated attribute  (https://github.com/bremor/bureau_of_meteorology/issues/189)...  I also changed weather.py as per https://github.com/bremor/bureau_of_meteorology/pull/190 and that makes the error go away.

**Comment by Makin-Things** [comment]
@Steve2017 not related to this issue. 1.1.20 is still the current release until either @bremor or I get time to check that the PR for 1.1.21 is in fact going to fix the issue properly. Closing this as the OP appears to have found a solution to his problem, which was related to HACS and not this integration.
