### ISSUE TITLE
Missing pressure and delta_t

### ISSUE THREAD

**Issue by bremor** [bremor/bureau_of_meteorology#19]
pressure and delta_t are not available from the new API - they can only be retrieved from FTP.

**Comment by DavidFW1960** [comment]
pressure isn't available for many FTP sites either. I believe its only obs stations that are at an airport.

**Comment by OkhammahkO** [comment]
That's a shame. Pressure would be handy for me... P.S Great work. Thank you.

**Comment by bremor** [comment]
This is in the pipeline, i want to add "opt in" pressure and delta_t sensors using FTP. Expect it in 3-4 weeks.

**Comment by tomlut** [comment]
Any chance of a dew point sensor too?

That was available on the old scraper integration and I use it (along with min forecast temp) to predict frost.

**Comment by bremor** [comment]
If BoM start providing pressure data through this API, I will add it into the integration, otherwise we miss out on pressure data  here.
