### ISSUE TITLE
Setup returns "Unsupported Lat/Lon"

### ISSUE THREAD

**Issue by ViperSC** [bremor/bureau_of_meteorology#195]
When clicking submit on the setup screen the error "Unsupported Lat/Lon" is returned

![image](https://github.com/bremor/bureau_of_meteorology/assets/92711862/68426772-73d7-4a2c-80a9-012a0a20c926)

**Comment by pauldingo** [comment]
Was this ever resolved? Thanks

**Comment by djferg** [comment]
I was unable to reproduce this issue using the lat/lon you supplied:

Lat: -33.634836282856085
Lon: 150.97251176834106

It completed the onboarding for Kenthurst successfully. Are you still having this issue?

Integration version 1.2.0 (commit f101761)
Home Assistant 2023.10.3

**Comment by jantoney** [comment]
I had the same issue upgrading from HA 2023.5 to 2023.11 (big jump I know).
I then upgraded the bureau_of_meteorology component to version 1.1.21 via HACS and that fixed it.

This issue seems to have been resolved and can probably be closed now.

**Comment by bjeanes** [comment]
I found I had to also restart HA after updating the BOM integration for this to go away.

**Comment by Makin-Things** [comment]
Stale.
