### ISSUE TITLE
depricated weather forecast

### ISSUE THREAD

**Issue by akvaran** [bremor/bureau_of_meteorology#198]
_This stops working in version 2024.3.0. Please address before upgrading_

The custom integration bureau_of_meteorology implements the forecast property or sets self._attr_forecast in a subclass of WeatherEntity.

Please create a bug report at https://github.com/bremor/bureau_of_meteorology/issues.

Once an updated version of bureau_of_meteorology is available, install it and restart Home Assistant to fix this issue.

**Comment by brendanheyu** [comment]
Here for this.

Such a moving target eh?

**Comment by akvaran** [comment]
Wish I was clever enough to fix it - kudos to those who are

**Comment by goncalvespedro** [comment]
Also having the same issue thanks.

**Comment by Roger-The-Paradox** [comment]
Isn't this the same as issue #189 ?

**Comment by jantoney** [comment]
> Isn't this the same as issue #189 ?

Yes - Duplicate of 189... This one should be merged or removed

**Comment by Makin-Things** [comment]
Duplicate of #189
