### ISSUE TITLE
1.2.0 - Regular failure to initialise on HA 2023.10.3

### ISSUE THREAD

**Issue by byrnecore** [bremor/bureau_of_meteorology#202]
Hey, 

I'm using Home Assistant 2023.10.3 with version 1.2.0 of the component, but notice that it constantly fails to initialize, but on the odd occasion when you reload it works. Mostly it's ina. failed state though

Any ideas?

**Comment by Makin-Things** [comment]
Sorry no idea and since no one else has reported any issue I can only assume it is a local problem.
