### ISSUE TITLE
Severe weather warnings

### ISSUE THREAD

**Issue by robhellstrom** [bremor/bureau_of_meteorology#205]
Hi it’s great getting weather forecasts etc into Hassio for various projects, but unless I have missed something I can’t see how to be push-notified by hassio of an impending hailstorm with only 15-20min notice as happened today when one struck and then I checked the BoM iPhone app itself.  It would be very handy to include all severe weather warnings (not just fire) into this integration if they are available.

**Comment by Makin-Things** [comment]
All warnings are already made available.
![image](https://github.com/bremor/bureau_of_meteorology/assets/91187456/8269243f-0888-49e5-abfd-33fcafa38b86)
You just need to figure out how you want to use them. There is no public documentation from the BoM about any of this, so it is all based on observing the values that pop up from time to time. We have put together a document with as much info as we have.
https://github.com/bremor/bureau_of_meteorology/blob/main/api%20doc/API.md
