### ISSUE TITLE
Feature request - Daily Solar radiation

### ISSUE THREAD

**Issue by ghost** [bremor/bureau_of_meteorology#206]
I'm trying to get data to calculate Evapotranspiration (using PyETo), and ideally would have total daily solar radiation data (along with daily T max/min, RH max/min, Avg wind speed).

Is there any way to access daily solar radiation from the API?

**Comment by theOzzieRat** [comment]
This is not something included in the BoM api used by the integration, so can't be done. The only items that are available is what is published in the BoM's mobile app.
