### ISSUE TITLE
Should mention Australia in name

### ISSUE THREAD

**Issue by romanr** [bremor/bureau_of_meteorology#207]
Until you look at repo you may think it's universal meteorology. And same goes for Australians looking for Australian weather component, skipping this one because components without country are usually U.S specific.

**Comment by Makin-Things** [comment]
I respectfully disagree. The logo for the component clearly says Australian Government with the aussie coat of arms.
Also it is too hard to change as it would most likely break everyone's installation. So it's not going to happen.

**Comment by romanr** [comment]
I don’t mean the id but displayed name, like,

`name": "Bureau of Meteorology (au)",`

You mentioned the logo, I installed and used it for a while and did n't see any logo.

**Comment by romanr** [comment]
> I respectfully disagree. The logo for the component clearly says Australian Government with the aussie coat of arms. Also it is too hard to change as it would most likely break everyone's installation. So it's not going to happen.

Yes, it says so on the logo. but that text is readable only for ants. It's unlikely that ants would be the majority of users looking to install this component for HA. 

___

<img width="250" height="60" alt="Image" src="https://github.com/user-attachments/assets/f652829f-5f0f-4302-9da5-c9f655785384" />

___

And the text in logo is not searchable, technology is not this advanced. When reinstalling I couldn't find it by searching anything Australia. 

Why not add "Australia" in the title when you can? It's like deliberately obfuscating it.
