### ISSUE TITLE
Deperciations in core 2024.1

### ISSUE THREAD

**Issue by tomlut** [bremor/bureau_of_meteorology#208]
Logger: homeassistant.const
Source: helpers/deprecation.py:204
First occurred: 13:51:47 (12 occurrences)
Last logged: 13:51:50

SPEED_KILOMETERS_PER_HOUR was used from bureau_of_meteorology, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfSpeed.KILOMETERS_PER_HOUR instead, please create a bug report at https://github.com/bremor/bureau_of_meteorology/issues
SPEED_KNOTS was used from bureau_of_meteorology, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfSpeed.KNOTS instead, please create a bug report at https://github.com/bremor/bureau_of_meteorology/issues

**Comment by tomlut** [comment]
Associated blog post:

https://developers.home-assistant.io/blog/2023/12/19/constant-deprecation/

**Comment by Makin-Things** [comment]
Need to add millimeters and celsius to  that as well.

LENGTH_MILLIMETERS was used from bureau_of_meteorology, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.MILLIMETERS instead, please create a bug report at https://github.com/bremor/bureau_of_meteorology/issues
TEMP_CELSIUS was used from bureau_of_meteorology, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/bremor/bureau_of_meteorology/issues
SPEED_KILOMETERS_PER_HOUR was used from bureau_of_meteorology, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfSpeed.KILOMETERS_PER_HOUR instead, please create a bug report at https://github.com/bremor/bureau_of_meteorology/issues
SPEED_KNOTS was used from bureau_of_meteorology, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfSpeed.KNOTS instead, please create a bug report at https://github.com/bremor/bureau_of_meteorology/issues

**Comment by tomlut** [comment]
Not sure why this is still open. It was fixed.
