### ISSUE TITLE
Problem with installation 

### ISSUE THREAD

**Issue by NYFB8888** [bremor/bureau_of_meteorology#209]
I have installed the BOM addon using  HACS installation procedure but all entities show  "Update" or "Up-to-date".
Overall, the addon does not work, can you suggest how to solve this problem?

<img width="776" alt="image" src="https://github.com/bremor/bureau_of_meteorology/assets/155231754/5557131c-953b-448f-aaa5-9fcad451dc80">

**Comment by Dragon0009** [comment]
i also cant seem to get it to work, it just dosent show up

**Comment by NYFB8888** [comment]
I have reinstalled the HA and installed the latest version of BOM 1.3.0 but
without success. It does not look like that is a problem with installation
but interfaces between HA and the addon.
Pity, it was a pretty good addn :(

**Comment by EvoSems** [comment]
Im unsure how to even find a configuration?

I have installed via HACS, but it seems I have no entities or any config file?

any help please?

thanks
