### ISSUE TITLE
Set rain_amount_max values to 0

### ISSUE THREAD

**Issue by mynameisdaniel32** [bremor/bureau_of_meteorology#21]
Would it be possible to set the forecast suburb_rain_amount_max_0, etc, values to be 0 when they're absent (and hence no rain forecast)?

This seems to work for the min values, but the max ones go to 'unkown' which is misleading (and breaks some automations I'm trying to do on numeric_state).

**Comment by bremor** [comment]
Great idea, I will get this out in the next release

**Comment by bremor** [comment]
Fixed in [0.8.1](https://github.com/bremor/bureau_of_meteorology/releases/tag/0.8.1)

**Comment by DavidFW1960** [comment]
So this should not apply to the range - I am seeing:
```
0 to 0mm
```
Should just show 0mm.

**Comment by bremor** [comment]
Thanks David! Good pickup. Reopening issues

**Comment by bremor** [comment]
Fixed in [0.8.3](https://github.com/bremor/bureau_of_meteorology/releases/tag/0.8.3)
