### ISSUE TITLE
will not accept tasmanian lat/long coordinates in setup

### ISSUE THREAD

**Issue by stevealt659** [bremor/bureau_of_meteorology#211]
![Screenshot at 2024-02-10 13-10-07](https://github.com/bremor/bureau_of_meteorology/assets/152834441/90a74e4c-c850-4290-9fb4-d39f4342faa9)

**Comment by systemtester** [comment]
Manually keyed in those coordinates and was presented with the nearest location.  Suggested an upgrade to latest version and/or restart of HA as all other variations of this issue have seen comments like that resolve this issue.
