### ISSUE TITLE
Concern with Precipipitation values for Hourly Forecast

### ISSUE THREAD

**Issue by kaizersoje** [bremor/bureau_of_meteorology#214]
I was looking at the precipitation for daily and hourly forecasts and I have a feeling the precipitation hourly forecasts may not be right as it is all zero. 

Daily forecast
![image](https://github.com/bremor/bureau_of_meteorology/assets/54566217/25dcfdb7-383b-430e-84d3-e5fcd66b4807)

Hourly Forecast
![image](https://github.com/bremor/bureau_of_meteorology/assets/54566217/d0cf2a8e-4256-4007-bad0-fcb243731029)

I have been trying to do do some debugging on my own. However, I could not find much documentation on how to do so.

**Comment by Makin-Things** [comment]
The integration uses the data as provided by the BoM as is used in the mobile app. You can compare against that.
