### ISSUE TITLE
Data missing on several weather cards

### ISSUE THREAD

**Issue by phoniclynx** [bremor/bureau_of_meteorology#216]
I've noticed that the BOM information might be labelling things wrong on a few different weather cards now. Not sure? 

Both the custom-weather and custom-card-weather (from HACS)  do not display the hPa value, and they do not display the wind speed. 

On the custom-weather for some reason it isn't showing the 5-day forecast correctly either., although that could just be the card itself perhaps.

![image](https://github.com/bremor/bureau_of_meteorology/assets/3883152/4fefdf93-98de-4730-8e5d-9400c79c6ab6)

![image](https://github.com/bremor/bureau_of_meteorology/assets/3883152/2e77847a-24d9-4c11-b748-5255a30bbf93)

**Comment by FaberO42** [comment]
+1

**Comment by Makin-Things** [comment]
The BoM do not provide air pressure info on the api so it is not possible to include that. The other issues appear to be a front end problem with the card being used.
