### ISSUE TITLE
Wind Gust in Knots?

### ISSUE THREAD

**Issue by Phil2336** [bremor/bureau_of_meteorology#218]
Not Sure if this came with the 1.3.0 Update I just installed,
But it appears that Wind Gusts are only available in Knots.

Entity is:- sensor.inverell_rs_gust_speed_knot

Currently Wind Speed Shows as 11km/h, & Gusts @ 9 Knots.

Changing the unit on the Entity does not rescale the Value, and I'd assume it is not meant to.

**Comment by Makin-Things** [comment]
I suspect you are using the wrong entity for gust. The BoM api provides both in the data and as such there are 2 entities for gust with different values.
