### ISSUE TITLE
Storm distance and bearing

### ISSUE THREAD

**Issue by alpha520098** [bremor/bureau_of_meteorology#219]
Feature Description:
The sensor should include the following capabilities:

**Storm Proximity Detection:** 

Ability to accurately measure the distance between the storm and the sensor location.

**Directional Bearing**
 Provide the compass bearing of the storm from the sensor's location, aiding in navigation and strategic planning.

**Real-Time Data:**

 Offer real-time updates on storm movement and intensity to facilitate timely decision-making.
Integration Friendly: Ensure compatibility with existing meteorological and navigation systems, allowing for seamless integration with home assistant. - this could also be used in things like audible warning using TTS and speakers 

This feature could significantly contribute to safety in various sectors including maritime, aviation, and disaster management by providing crucial data to avoid severe weather conditions. Additionally, it could enhance the accuracy of weather forecasts and modeling.

Thank you for considering this feature request

**Comment by Makin-Things** [comment]
Sorry this is simply not possible with the data the BoM provide.
