### ISSUE TITLE
Icons in weather platform

### ISSUE THREAD

**Issue by neponn** [bremor/bureau_of_meteorology#22]
Loving the new weather platform. I think the `condition` mapping needs to be fixed up to allow the existing Lovelace weather cards to find the correct icon. Rather than, for example, `Mostly sunny.`, I *think* the `condition` should be `sunny`.

From what I can tell, the mapping can be found in [`src/data/weather.ts`](https://github.com/home-assistant/frontend/blob/c1dba462e8d1b060b86c3c15c269af966506a711/src/data/weather.ts#L15) in the home assistant frontend.

```ts
export const weatherSVGs = new Set<string>([
  "clear-night",
  "cloudy",
  "fog",
  "lightning",
  "lightning-rainy",
  "partlycloudy",
  "pouring",
  "rainy",
  "hail",
  "snowy",
  "snowy-rainy",
  "sunny",
  "windy",
  "windy-variant",
]);
```

I think the same may also be true for the `state` of the `weather` entity.

Using the built in `weather-forecast` card, I get:

<img width="430" alt="Screen Shot 2020-11-08 at 11 35 34 am" src="https://user-images.githubusercontent.com/32885870/98454244-868bb780-21b6-11eb-846f-5d7500f0d64f.png">

You can see that the main icon is incorrect, and none of the forecast icons are showing.

**Comment by DavidFW1960** [comment]
It's going to be reading the condition from the API and sunny, mostly sunny are both valid conditions.

**Comment by neponn** [comment]
Hi @DavidFW1960 - yes indeed, so there will need to be some sort of translation from the BOM API to something that the `weather` platform Lovelace cards expect. A bit like needed to be done in the recent `mdi_icon` update. The current `condition` values are valid for the BOM API, but not in line with what is expected of a `weather` platform. Here you can see an example of what is currently being produced.

<img width="1096" alt="Screen Shot 2020-11-08 at 12 14 51 pm" src="https://user-images.githubusercontent.com/32885870/98454733-036d6000-21bc-11eb-962a-72accc41ee45.png">

My guess is that @bremor's integration will need to make a translation from the BOM API value to one of the entries quoted in my original post.

**Comment by bremor** [comment]
No worries! I will look into this.

**Comment by neponn** [comment]
Awesome! By the way, here's how the `weather` platform looks for the `OpenWeatherMap` integration. This one works fully with the Lovelace cards (mind you, the forecast itself is pretty ordinary!). You can see the condition names it uses.

<img width="1007" alt="Screen Shot 2020-11-08 at 8 33 46 pm" src="https://user-images.githubusercontent.com/32885870/98461617-b4e2b480-2201-11eb-9109-514286278ed4.png">

**Comment by austwhite** [comment]
Does BoM provide a status for night?   I don't recall seeing that at all before.   That would mean Clear-Night will never show.  I have only found Dark Sky and WeatherBit to actually show that condition.

**Comment by bremor** [comment]
BoM just provide ‘clear’ as the condition for clear-night. I have a working version of this in my own environment so will release this weekend

**Comment by austwhite** [comment]
Cool.   Maybe it can detect if sun is below horizon to distinguish between clear day and clear night.

**Comment by bremor** [comment]
I would’ve thought clear-day would be better known as "sunny" 😉

**Comment by DavidFW1960** [comment]
> Cool. Maybe it can detect if sun is below horizon to distinguish between clear day and clear night.

This is how mu cards detect it and change the icon accordingly

**Comment by DavidFW1960** [comment]
> BoM just provide ‘clear’ as the condition for clear-night. I have a working version of this in my own environment so will release this weekend

Let me know before you change any of the conditions as I will need to change the card to account for it.

**Comment by austwhite** [comment]
> This is how mu cards detect it and change the icon accordingly

I think the developer of WeatherBit did this as well as originally his integration did not detect night, but he added it later

**Comment by bremor** [comment]
> > BoM just provide ‘clear’ as the condition for clear-night. I have a working version of this in my own environment so will release this weekend
> 
> Let me know before you change any of the conditions as I will need to change the card to account for it.

It’s for the weather entity only, so shouldn’t affect your card right?

**Comment by DavidFW1960** [comment]
Yeah.. if it's the weather entity no problem. It's an easy fix on the card anyway if you changed the icon_* ones - I would just add a new condition which is easy as long as I know about it. The card uses a different icon after sunset for conditions that I have night icons for.

**Comment by bremor** [comment]
Fixed in [0.8.2](https://github.com/bremor/bureau_of_meteorology/releases/tag/0.8.2)

**Comment by neponn** [comment]
That's awesome @bremor - working nicely. Just one thing... the mapping to `mdi:weather-light-showers` I think should instead by to `mdi:weather-drizzle`. HA (or I) can't find an icon for `mdi:weather-light-showers`. Let me know if I should open  a new issue.

Thanks again - this is coming to together so quick!

**Comment by bremor** [comment]
Hey good find, I should probably revisit "light_rain" aswell... is there any real difference between light rain and light showers? I think I should probably make them all `mdi:weather-drizzle`. Thoughts?
```
    "light_rain": "mdi:weather-partly-rainy",
    "light_shower": "mdi:weather-light-showers",
    "light_showers": "mdi:weather-light-showers",
```

**Comment by biffel** [comment]
Awesome work @bremor. Apologies for the resurrection, but this thread seems to align with a current issue I have.

The icon mdi:weather-light-showers is currently being output for my location - and this icon doesn't exist in my implementation (2022.6.6). Did you ever end up looking into tidying up the mdi icon names output into the location_mdi_icon_N sensors?
