### ISSUE TITLE
Missing barometric pressure

### ISSUE THREAD

**Issue by VlastiBroucek** [bremor/bureau_of_meteorology#221]
Hello,

I noted that barometric pressure is missing. The reason probably is that for example for Devonport Airport, the API call you use 
https://api.weather.bom.gov.au/v1/locations/r28jd2/observations
does not return that value.

However, there is another possible call
http://www.bom.gov.au/fwo/IDT60801/IDT60801.95960.json
that returns barometric pressure and some other details.

Have you considered using this call?

**Comment by FaberO42** [comment]
+1

**Comment by Makin-Things** [comment]
The integration uses the API used by the BoM mobile app. It does not provide barometric pressure so it is not available. Unless the BoM decide to include it in the mobile app it will neo ever be added.
