### ISSUE TITLE
Updating state took 1.396 seconds

### ISSUE THREAD

**Issue by tomlut** [bremor/bureau_of_meteorology#223]
Receiving this warning in the logs:

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1176
First occurred: 13:32:51 (1 occurrences)
Last logged: 13:32:51

Updating state for sensor.hobart_temp (<class 'custom_components.bureau_of_meteorology.sensor.ObservationSensor'>) took 1.396 seconds. Please create a bug report at https://github.com/bremor/bureau_of_meteorology/issues

**Comment by Makin-Things** [comment]
Probably a BoM issue.

**Comment by tomlut** [comment]
I forgot about this. Yeah could have been. I haven't seen the warning since.
