### ISSUE TITLE
Is Barometric Pressure retrievable via API?

### ISSUE THREAD

**Issue by DrewXT** [bremor/bureau_of_meteorology#224]
I'll ask the smart people, because I can't code - is it possible to retrieve Pressure via the API?

I can see pressure is published via the Observations site, but it's not retrieved by the Integration http://www.bom.gov.au/products/IDV60901/IDV60901.94870.shtml

Is this something that is easy to add in?  OpenWeatherMap have changed their billing structure, which makes them unappealing

**Comment by Makin-Things** [comment]
Duplicate #221
