### ISSUE TITLE
Renamed a bunch of sensors?????

### ISSUE THREAD

**Issue by DavidFW1960** [bremor/bureau_of_meteorology#23]
Did you rename a bunch of sensors?

**Comment by bremor** [comment]
Nope don't think so, what are you seeing?

**Comment by DavidFW1960** [comment]
yeah you did. I only noticed it cos day 6 was different. Ended up removing old one and adding integration again. I then spent the last few hours updating the dosc.
sensor.gosford_wind_speed > sensor.gosford_wind_speed_kilometre
sensor.gosford_temperature > sensor.gosford_temp
sensor.gosford_temperature_feels_like > sensor.gosford_temp_feels_like
sensor.kariong_min* > sensor.kariong_temp_max*
sensor.kariong_min* > sensor.kariong_temp_max*
sensor.kariong_icon* > sensor.kariong_icon_descriptor*
sensor.gosford_gust_speed > sensor.gosford_gust_speed_kilometre
sensor.gosford_wind_speed > sensor.gosford_wind_speed_kilometre
sensor.gosford_gust_speed_knots > sensor.gosford_gust_speed_knot
sensor.gosford_wind_speed_knots > sensor.gosford_wind_speed_knot
