### ISSUE TITLE
Forecast not updating current conditions

### ISSUE THREAD

**Issue by mitch-1211** [bremor/bureau_of_meteorology#230]
Hi @bremor, thanks for making this great integration!

I've got a question re: the forecast sensor, it seems as though the current conditions are not updated regularly, is there a way to set the update interval?

See below screenshot:
<img width="597" alt="Screenshot 2024-07-13 at 11 19 40 am" src="https://github.com/user-attachments/assets/cd94d62c-5776-4c2e-b3be-2c1eb43c3ed3">

The hourly forecasts are correct in that, at the time I took the screenshot it was 11:20 AM, so the hourly forecast is showing from 11AM onwards. However the current conditions at the top of the card have not been updated for 13 hours.

**Comment by mitch-1211** [comment]
See #231 for workaround

**Comment by DanielKinsman** [comment]
I get something similar even with 1.3.3. Using the weather card showing the hourly forecast on a tablet mounted to my wall with the screen always on, the hours never update if left untouched. However the instant I open the same view on a different device it will refresh even on the wall tablet.

There are no timezone errors or anything obvious in the logs.

**Comment by willat8** [comment]
> I get something similar even with 1.3.3. Using the weather card showing the hourly forecast on a tablet mounted to my wall with the screen always on, the hours never update if left untouched. However the instant I open the same view on a different device it will refresh even on the wall tablet.
> 
> There are no timezone errors or anything obvious in the logs.

I also see this behaviour.
