### ISSUE TITLE
<suburb> Min 0 not being set 

### ISSUE THREAD

**Issue by leeiberry** [bremor/bureau_of_meteorology#24]
this value have not been set ..   (null)
come thru as NaN in the bom-weather-card

**Comment by DavidFW1960** [comment]
BOM zeros these out around 4PM every day. It's annoying but this is why I use template sensors for when it happens.

**Comment by bremor** [comment]
Are you taking about rain_amount_min_0 or temp_min_0?

**Comment by leeiberry** [comment]
Temp

**Comment by DavidFW1960** [comment]
Me? Temperature. Other things disappear at 10PM as well

**Comment by bremor** [comment]
> Temp
> […](#)

Thanks, this is a known issue but it’s good to now have it here, I am hoping to fix this in an upcoming release

**Comment by leeiberry** [comment]
Thanks

**Comment by bremor** [comment]
Fixed in [0.8.3](https://github.com/bremor/bureau_of_meteorology/releases/tag/0.8.3)
