### ISSUE TITLE
Set basename for sensors in integration

### ISSUE THREAD

**Issue by glenn20** [bremor/bureau_of_meteorology#25]
It would be helpful to set an override basename for the sensors generated by the integration like some other integrations do (eg. when first configuring the integration - but also to allow renaming).

I share automations across multiple sites and it is helpful to use the same name at all sites (eg. "home", instead of suburb name). I think this would be useful for many others using automations.

(BTW - thanks for the integration - it took me a while to find it after I lost the bom integration in 0.117 - but this is looking like a really excellent replacement.)

**Comment by bremor** [comment]
Yes... great idea! I'm thinking custom basename for observations, and custom basename for forecasts, and you can set them to be the same if you wish, otherwise they will default to the weather station and the suburb name respectively.

**Comment by glenn20** [comment]
That sounds perfect - thanks for the enthusiastic response. It would also be helpful to provide an attribute or sensor with the names of the location and weather station (if there isn't one already).

It would also be easier to share configs for @DavidFW1960 's bom-weather-card if we adopted a simple convention - like "bom-home" or "bom-weather" as the basename.

**Comment by bremor** [comment]
Feature added in 0.9
