### ISSUE TITLE
Error in log since update

### ISSUE THREAD

**Issue by craigmcewen** [bremor/bureau_of_meteorology#29]
Hey!

Updated the integration this evening and since the update I have stopped seeing info come through, I did attempt to re-install and the same error occurs, no updates were flowing through for any of the existing sensors, I have provided the error from the log hopefully that can be of some help! I guess to note also that it does list Ingleburn below but it was providing data for both the suburb and the closest weather station (Holsworthy) and they have both flicked to "unavailable"

`Logger: homeassistant.config_entries
Source: custom_components/bureau_of_meteorology/PyBoM/collector.py:115
First occurred: 1:57:30 AM (1 occurrences)
Last logged: 1:57:30 AM

Error setting up entry Ingleburn for bureau_of_meteorology
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 234, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/bureau_of_meteorology/__init__.py", line 28, in async_setup_entry
    await collector.get_daily_forecasts_data()
  File "/config/custom_components/bureau_of_meteorology/PyBoM/collector.py", line 107, in get_daily_forecasts_data
    await self.flatten_forecast_data()
  File "/config/custom_components/bureau_of_meteorology/PyBoM/collector.py", line 115, in flatten_forecast_data
    flattened["mdi_icon"] = MDI_ICON_MAP[icon]
KeyError: None`

**Comment by craigmcewen** [comment]
Whatever was causing the issue seems to have resolved itself, the integration has updated from BOM.

**Comment by bremor** [comment]
Re-opening this issue. I know what's causing it and should be fixed in next release.

**Comment by bremor** [comment]
Fixed in [0.8.2](https://github.com/bremor/bureau_of_meteorology/releases/tag/0.8.2)
