### ISSUE TITLE
Invalid config

### ISSUE THREAD

**Issue by JerryCih** [bremor/bureau_of_meteorology#31]
I am getting message in notifications:

Invalid config
The following integrations and platforms could not be set up:
bureau_of_meteorology.sensor
bureau_of_meteorology.weather
Please check your config.

removed the component already few time and restarted HA but no change.

**Comment by bremor** [comment]
Did you install using HACS?

**Comment by bremor** [comment]
Is there any more details in your logs?

**Comment by JerryCih** [comment]
Imstalled using HACS. Logs is showing this:

Logger: homeassistant.setup
Source: setup.py:280
First occurred: November 15, 2020, 11:30:54 PM (2 occurrences)
Last logged: November 15, 2020, 11:30:58 PM

Unable to prepare setup for platform bureau_of_meteorology.weather: Platform not found (cannot import name 'LENGTH_MILLIMETERS' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).
Unable to prepare setup for platform bureau_of_meteorology.sensor: Platform not found (cannot import name 'LENGTH_MILLIMETERS' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).

Could be some sort of conflict with open weather map? reason for asking becaise logs also shows this:

Logger: homeassistant.components.weather
Source: helpers/entity_platform.py:121
Integration: Weather (documentation, issues)
First occurred: November 15, 2020, 11:30:54 PM (1 occurrences)
Last logged: November 15, 2020, 11:30:54 PM

The openweathermap platform for the weather integration does not support platform setup. Please remove it from your config.

When I have some time I might remove open weather map and see.

**Comment by bremor** [comment]
Cool! You need to be running Home Assistant version 0.116.0 or later for this component. Earlier versions do not have the built in constants `LENGTH_MILLIMETERS `and `PERCENTAGE` so you will have to comment them out, and manually define them like below, OR upgrade your Home Assistant.

If you want to modify the code to be compatible with earlier versions of Home Assistant change the following in `custom_components\bureau_of_meteorology\sensor.py`, but please note that when you update this component it will override your changes.

```
from homeassistant.const import (
    ATTR_ATTRIBUTION,
    DEVICE_CLASS_HUMIDITY,
    DEVICE_CLASS_TEMPERATURE,
    DEVICE_CLASS_TIMESTAMP,
    #LENGTH_MILLIMETERS, <----- Comment out this line using the #
    #PERCENTAGE, <----- Comment out this line using the #
    TEMP_CELSIUS,
)
LENGTH_MILLIMETERS = "mm" # <---Add this line
PERCENTAGE = "%" # <---Add this line
```

**Comment by JerryCih** [comment]
thx Bremor, updated and it works now.
