### ISSUE TITLE
Ability to configure which sensors are created

### ISSUE THREAD

**Issue by theOzzieRat** [bremor/bureau_of_meteorology#32]
I have two observation stations at a similar distance, but the one slightly further away generally matches the conditions at my house more closely. When I add the integration to get the forecast for my location it also adds that observations for the station that I don't want. Then when I add the integration with coordinates to get the observations I want I also get the forecast for that location (which I definitely don't want). This means I end up with 130 sensors which are of no use to me.

It would be good if when configuring the integration that you could select if you want observations, forecast or both (default both would be sensible) to avoid having lots of sensors being created.

**Comment by bremor** [comment]
Thanks Simon. I am planning to do-over the onboarding for this integration and include this functionality. Maybe even the option to exclude certain sensors, for example, I do not care for UV data but that creates 28 sensors..

**Comment by theOzzieRat** [comment]
Awesome. My thoughts are that it potentially should be split into 2 integrations (bom_forecast and bom_observations) due to the data being for different locations and of completely different types. I actually think the same should be done for the weather card, so that you can add and display any combination of weather info you desire (I am planning on adding a local weather station into my mix as well, this wil just use mqtt for the sensors though and nothing to do with your integration).

**Comment by DavidFW1960** [comment]
``` I actually think the same should be done for the weather card, so that you can add and display any combination of weather info you desire```
I don't understand what you mean by this. The weather card (my one) already does exactly this now.

**Comment by bremor** [comment]
Feature added in 0.9
