### ISSUE TITLE
Day 7 never appears

### ISSUE THREAD

**Issue by bremor** [bremor/bureau_of_meteorology#36]
If this integration is installed when day 7 data is unavailable, it will never create sensors for the day 7 forecast.

**Comment by bremor** [comment]
I reloaded the component the other day, and the forecast didn’t actually even have day 6. Need to figure out the best way to handle this. Create dummy sensors anticipating that there eventually be a day 6 appear in the data?

**Comment by DavidFW1960** [comment]
I think that's best. Give them unknown as the state.

**Comment by bremor** [comment]
Fixed in 0.9
