### ISSUE TITLE
No Wind Records for Weather stations

### ISSUE THREAD

**Issue by ssna** [bremor/bureau_of_meteorology#38]
I used old BOM to monitor wind records at North Head, Airport etc.  Is it possible to get these back.

**Comment by bremor** [comment]
Sorry, I'm not really sure what you mean. This does have some wind data.. what exactly are you missing?
![image](https://user-images.githubusercontent.com/34525505/99757475-8939c580-2b43-11eb-9c7d-31e7724f85c3.png)
