### ISSUE TITLE
Forcasts disappeared

### ISSUE THREAD

**Issue by leogaggl** [bremor/bureau_of_meteorology#39]
I had the custom weather card working well for a few days and all of a sudden the forecasts have seem to have disappeared.

![bom-custom](https://user-images.githubusercontent.com/199995/99896728-3e56b400-2ce3-11eb-9578-fd93c1e9d663.png)

There is no errors at all in the logs and everything else is operating normally.

Any pointers on how to troubleshoot further?

**Comment by bremor** [comment]
Anything interesting in your logs? What is your geohash? Does it resolve after a reboot?

**Comment by leogaggl** [comment]
Nothing in the logs at all. Tried to reboot and still the same.

However, it has resolved itself just now (about 6 hours later). Unsure as to how I could find the cause.

Will resolve the issue. Any pointers for future debugging are appreciated.

**Comment by bremor** [comment]
If it breaks again, try browsing to these URLS to see if they work, but put your own geohash code in the URL. You can get your geohash code if you enable debug level logging for this component.
https://api.weather.bom.gov.au/v1/locations/r1f3pw/observations
https://api.weather.bom.gov.au/v1/locations/r1f3pw/forecasts/daily

Put this on your config to enable debugging.
```
logger:
  default: warn
  logs:
    custom_components.bureau_of_meteorology: debug
```

**Comment by leogaggl** [comment]
Thanks for the info. Much appreciated. Will check this next time it happens.

Thanks for the great work on the integration. It's highly useful!

**Comment by leogaggl** [comment]
The same issue has been occurring for last days and I managed to locate the root cause of the issue. 

When I use my geohash from the debug logs the "forecasts" endpoint actually returns the NULL values. 

https://api.weather.bom.gov.au/v1/locations/r1f88p/forecasts/daily

Question is now how to change the setup as it doesn't seem to be exposed with an edit function anywhere in the UI.

**Comment by leogaggl** [comment]
#56 This seems to be related.

**Comment by AWoodley** [comment]
@leogaggl I'm not sure #56 is related - in that issue the remainder of the forecast is present, and only the short_text is null. I have verified this is the case in the json provided by the BoM API.

**Comment by bremor** [comment]
@leogaggl When I have looked at your location URL, it seems fine. When it's not working for you can you please copy/paste the contents of the URL?

**Comment by bremor** [comment]
@leogaggl 
I'm closing this one for now, please comment/reopen if required.
