### ISSUE TITLE
Unknown Error when adding component

### ISSUE THREAD

**Issue by andybowser** [bremor/bureau_of_meteorology#4]
<img width="400" alt="image" src="https://user-images.githubusercontent.com/485249/97518105-aff45880-19ea-11eb-96e1-1a1fa858cbbe.png">
I get the above error when trying to add the component and input the latitude and longitude.

**Comment by bremor** [comment]
Anything in your logs? What version of HA are you running? Running latest version of the component? v0.5

**Comment by DavidFW1960** [comment]
Just a thought.. did you restart HA after you added the component?

**Comment by andybowser** [comment]
```
Logger: custom_components.bureau_of_meteorology.config_flow
Source: custom_components/bureau_of_meteorology/PyBoM/collector.py:66
Integration: Bureau of Meteorology (documentation, issues)
First occurred: 13:48:21 (1 occurrences)
Last logged: 13:48:21
Unexpected exception

Traceback (most recent call last):
  File "/config/custom_components/bureau_of_meteorology/config_flow.py", line 36, in async_step_user
    result = await collector.get_observations_data()
  File "/config/custom_components/bureau_of_meteorology/PyBoM/collector.py", line 47, in get_observations_data
    await self.flatten_data()
  File "/config/custom_components/bureau_of_meteorology/PyBoM/collector.py", line 66, in flatten_data
    for sub_observation in self.observations_data["data"][observation]:
TypeError: 'NoneType' object is not iterable
```
The above is in my logs. I am running 0.117 and 0.5.
I have restarted a couple of times.

**Comment by bremor** [comment]
Can you please share what co-ordinates you are entering? Send them via email (or even modify them slightly) if you have privacy concerns, moran.brendan@outlook,com

**Comment by andybowser** [comment]
-33.8xxxxxxxxxxxx44
151.1xxxxxxxxx77

Hope that isn't too filtered. They are entered automatically on adding the component. I presume it's from my configuration.

I also tried the co-ordinates from here https://api.weather.bom.gov.au/v1/locations/r3gx2f8/

**Comment by bremor** [comment]
I can see what the issue is, your weather station, "Sydney - Observatory Hill" is missing gust data. I will work on a new release that will work with missing gust data.
```
{
   "metadata":{
      "response_timestamp":"2020-10-29T03:07:30Z",
      "issue_time":"2020-10-29T03:01:02Z"
   },
   "data":{
      "temp":22,
      "temp_feels_like":20.5,
      "wind":{
         "speed_kilometre":17,
         "speed_knot":9,
         "direction":"SSE"
      },
      "gust":null,
      "rain_since_9am":0,
      "humidity":66,
      "station":{
         "bom_id":"066214",
         "name":"Sydney - Observatory Hill",
         "distance":4651
      }
   }
}
```

**Comment by bremor** [comment]
Just released v0.6 where it should be resolved.

**Comment by andybowser** [comment]
Resolved. 
Many thanks.

**Comment by DavidFW1960** [comment]
So Brendan... can the same fix be done for day 6? Also last night around 10 the UV/Fire data disappeared and the minimum goes to null as well. Can null just return unknown maybe or n/a?

**Comment by bremor** [comment]
> So Brendan... can the same fix be done for day 6? Also last night around 10 the UV/Fire data disappeared and the minimum goes to null as well. Can null just return unknown maybe or n/a?

When they disappear, they become "None" in Python, which translates to a state of "unknown" in HA.
I'm not sure what the best/most elegent way is to handle each scenario when data disappears temporarily. I could probably code it in so it retains it's existing state.?

**Comment by DavidFW1960** [comment]
> I could probably code it in so it retains it's existing state.?

Sounds like a good idea...
