### ISSUE TITLE
Integration no longer showing up or searchable in HA/Configuration/Integrations.

### ISSUE THREAD

**Issue by david-taylor** [bremor/bureau_of_meteorology#41]
Hi. Title pretty well says all. I have a fresh install supervised Home Assistant 0.118.3 on Ubuntu 20.04 server. Unable to find your integration. About 6 months ago I had it and was impressed.

Also a suggestion that all would benefit from is the animation of the last 24 hours of the half hourly satellite image. No need for localisation information as it is Australia wide.

**Comment by bremor** [comment]
Hey mate, can you please paste some screenshots of what you are experiencing so I can understand the issue a bit better?

**Comment by david-taylor** [comment]
Not a problem.
[image: Screenshot from 2020-11-25 16-41-19.png]

**Comment by DavidFW1960** [comment]
> Hi. Title pretty well says all. I have a fresh install supervised Home Assistant 0.118.3 on Ubuntu 20.04 server. Unable to find your integration. About 6 months ago I had it and was impressed.
> 
> Also a suggestion that all would benefit from is the animation of the last 24 hours of the half hourly satellite image. No need for localisation information as it is Australia wide.

Have you installed this custom component? This component is less than 1 month old so not sure how you used it 6 months ago. I think you might be confused.

Please check the instructions in the readme and preferably install the component using HACS then after restarting, add the integration in the GUI (Search for Bureau not BOM). It will pop right up.
