### ISSUE TITLE
no longer working after last update

### ISSUE THREAD

**Issue by robertfgoodworth** [bremor/bureau_of_meteorology#43]
My BOM stopped working after the last update, how do I reverse this last update?

**Comment by bremor** [comment]
Thanks for the detailed post! Are you interested in fixing it or did you just want to stay at that older version forever? Did you read the [release notes](https://github.com/bremor/bureau_of_meteorology/releases/tag/0.9), or did you just blindly update and hoped for the best? Did you notice the big bold writing that said “breaking change”? If you want to go back to an older version, figure it out yourself, it can all be done within the GUI you just have to click the right things. If you want help fixing it, I will definitely help, just make sure you’ve tried at least some base level of troubleshooting on your own, and then come back with screenshots and logs from your system.

**Comment by robertfgoodworth** [comment]
Sorry, i just clicked update, no warning this will break, I should make a habit of reading release notes. All working again. Thanks

**Comment by robertfgoodworth** [comment]
all working again.
