### ISSUE TITLE
Basename for Forecasts

### ISSUE THREAD

**Issue by mynameisdaniel32** [bremor/bureau_of_meteorology#44]
The latest version (0.9) asks to configure a custom basename when setting up for both sensors and forecasts, but this doesn't seem to affect entity IDs or sensor names for the forecasts only, with them all created using the format 'sensor.suburb_min_temp_0' etc. I tried to have them created using the prefix BOM Suburb.

I removed the previous integration, updated, restarted, then set up again. But maybe something got left behind?

Setting a basename for sensors at a BOM station work perfectly.

**Comment by bremor** [comment]
Thanks for that, obviously I suck at testing. Will fix soon.

**Comment by bremor** [comment]
Fixed in 0.9.1
