### ISSUE TITLE
Show date for forcast

### ISSUE THREAD

**Issue by NovaGL** [bremor/bureau_of_meteorology#46]
Is there anyway we can see the date the forecast refers to rather than 0 - 7

Eg 29 Nov 2020 as a field.

**Comment by DavidFW1960** [comment]
The date is already an attribute isn't it? The starting time..

**Comment by NovaGL** [comment]
No that date refers to when the data was updated not the date of the forecast

**Comment by bremor** [comment]
You are quite right NovaGL - This was an oversight on my part. It is included in the weather entity, but not in the sensors.
My intention would be to create a "date' attribute on each sensor, which would be the RFC 3339 formatted date received from BoM which would look like this:

`2020-11-30T13:30:00Z`

This is not particular readable and would require you to create a template sensor to get a more user friendly date.

Formatting dates with Python is trivial so I could also easily create a second attribute with a more readable date, e.g. Mon, 30 Nov

**Comment by NovaGL** [comment]
I don't want new sensors for each I want one sensor per day with date icon Max temp and short description I don't see the need for an icon sensor

**Comment by bremor** [comment]
Well then, please feel free to use a template sensor to get exactly what you want:
https://www.home-assistant.io/integrations/template/

I will be adding date as an attribute in the next release.

**Comment by NovaGL** [comment]
Great. Thanks for your help. Feel free to close this issue when done.

**Comment by bremor** [comment]
Fixed in release 0.10.1
