### ISSUE TITLE
Very stupid question on Install

### ISSUE THREAD

**Issue by mpancino** [bremor/bureau_of_meteorology#47]
How do you set the location for the sensors? The Weathercard implies its automatically picked up by HA, but the sensor are not showing up after install and reboot. Sorry guys, im normally about to work this out.

**Comment by bremor** [comment]
Do you have HACS running on your system? Have you added this integration via HACS? Where is anything implied? What is a Weathercard? More details please.

**Comment by bremor** [comment]
No response so I’m closing this issue.
