### ISSUE TITLE
Not an issue, just a typo

### ISSUE THREAD

**Issue by muzzak123** [bremor/bureau_of_meteorology#48]
The sensor Gust Speed Knot shows as Gust Speed Know when completing the initial configuration setup

**Comment by bremor** [comment]
Good pickup! Thanks, will fix with next release.

**Comment by kaizersoje** [comment]
Yeah I noticed it too. Was going to raise an issue and then saw that there is one already raised to address this.

**Comment by bremor** [comment]
Fixed in release 0.10.1
