### ISSUE TITLE
Weather entity not created with custom basename

### ISSUE THREAD

**Issue by kaizersoje** [bremor/bureau_of_meteorology#49]
I created Observation and Forecast sensors with a custom base name. However, I noticed that the `weather` entity got created with the original location for forecast and not the custom base name.

**Comment by bremor** [comment]
Good point.

How would you like this to look? Should it take the name from forecasts, observations or it’s own name?

**Comment by kaizersoje** [comment]
I would guess from the forecasts.

**Comment by bremor** [comment]
Fixed in release 0.10.1
