### ISSUE TITLE
Update interval seems long. bug?

### ISSUE THREAD

**Issue by chicaneau** [bremor/bureau_of_meteorology#52]
Hey @bremor thanks for your work on this, it's great you've filled the void since hass removed the core component. 

I have set it up and it appears to work, however it's telling me the last update was 16 hours ago? the weather/temp etc changes considerably over this period. Your readme says should update 10 minutely. There's not much configuration to this, am i missing something?

![image](https://user-images.githubusercontent.com/26127713/101096181-ea18d180-360a-11eb-8245-1e4e066928cf.png)

**Comment by bremor** [comment]
Can you confirm that the temp and humidity also don’t change during this period? I think that 16 hours will only be reset unless the ‘state’ changes which is “Mostly clear” in your screenshot

**Comment by chicaneau** [comment]
Yeh, the temp hasn’t changed in ages. I’ve had a template sensor tracking it for 2 days now
![C7189475-D217-4391-83D9-9F470192EB57](https://user-images.githubusercontent.com/26127713/101148542-7823a500-3669-11eb-9b69-f7f84cc1e347.jpeg)

**Comment by dave-schwarz** [comment]
getting this error thats related I think 

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/bureau_of_meteorology/sensor.py", line 62, in async_setup_entry
    if config_entry.data[CONF_OBSERVATIONS_CREATE] == True:
KeyError: 'observations_create'

**Comment by chicaneau** [comment]
Hi @bremor Can you please explain so i understand correctly, does the temperature now only update when the 'state' changes? such as clear to raining or something? That doesn't really make much sense, the component used to work brilliantly until it all got combined into the one weather integration. Now its almost useless as its only updating around twice a day if im lucky.
![image](https://user-images.githubusercontent.com/26127713/101718643-63259680-3aed-11eb-8111-636fc8285348.png)

**Comment by bremor** [comment]
Yeah mate it would appear to be a bug and you are right it is quite useless as it is. Unfortunately I have a 5 day old baby at home so won’t be able to get around to this in a hurry. There is a pull request to fix this but I haven’t had a chance to review and test

**Comment by DavidFW1960** [comment]
What am I missing here?
![image](https://user-images.githubusercontent.com/36390762/101720189-0af49180-3af9-11eb-8bed-bafe246226e0.png)

**Comment by bremor** [comment]
He is talking about the weather entity I believe, not the sensor entities

**Comment by DavidFW1960** [comment]
Congrats on the new baby too BTW.

**Comment by chicaneau** [comment]
Didn’t all of the sensor entities get replaced? Mine all vanished and I
only have a weather entity. Is there any way to bring them back? Or just
downgrading the only option? There’s no real configuration it seems.

**Comment by DavidFW1960** [comment]
Remove the integration and add it again.. there were some breaking changes. There are also options you need to select when you add it back.

**Comment by dave-schwarz** [comment]
did this today and its now updating every 10 minutes fine.
However the state seems to be two states, not sure how this can be addressed, but I want to trigger automations to move shades when it sunny, and the states seem to be things like
Mostly sunny.
sunny
exceptional
Showers. Windy.
Partly cloudy.
Early shower. Sunny afternoon.

I would prefer it to be the default weather states if possible

‘clear-night’
‘cloudy’
‘fog’
‘hail’
‘lightning’
‘lightning-rainy’
‘partlycloudy’
‘pouring’
‘rainy’
‘snowy’
‘snowy-rainy’
‘sunny’
‘windy’
‘windy-variant’
‘exceptional’

and the BOM attributes are in a BOM specificat variable

**Comment by DavidFW1960** [comment]
Whose default weather states?
This is where template sensors are useful..

**Comment by tathamoddie** [comment]
Should be fixed by #53.

**Comment by bremor** [comment]
Thanks for your help guys, I have released a beta version 0.10 that would be great if we could test before general release.

**Comment by bremor** [comment]
Hopefully this is working well for everyone now. Closing this issue.

@DavidFW1960 Thanks mate :) My brain has been way to foggy to do any coding with the new baby around.
