### ISSUE TITLE
Some BoM stations report null short_text

### ISSUE THREAD

**Issue by AWoodley** [bremor/bureau_of_meteorology#56]
I found that my local forecast would have 'null' for the short_text. This resulted in hass showing 'Unknown' in the weather forecast card.

#54 This is a short hack to generate the condition/state from the first part of the extended_text.

Example forecast: https://api.weather.bom.gov.au/v1/locations/qd6dv8/forecasts/daily

**Comment by bremor** [comment]
Hey Adrian, Thanks so much for your pull request, but I have decided to go with the "standard" states for the 'weather.placename' entity, as per issues #55. so short text missing won't be a problem going forward because it won't be used for the state.

**Comment by bremor** [comment]
Fixed in release 0.10.1
