### ISSUE TITLE
Option to choose alternative/multiple Observation stations

### ISSUE THREAD

**Issue by DavidWicks** [bremor/bureau_of_meteorology#60]
Hi, I have just upgraded to your new integration and everything is working great.  The issue I am haveing is that the closest observation station selected does not provide all necessary sensor information.  `Humidity` and `Feels like Temperature` to name a couple.  My next nearest station has all this information available.  Is it possible to select another/multiple observation stations while keping my local location for forecast info ?

My current station is `hillarys_point_boat_harbour`
I would prefer to select `Swanbourne`

Thanks !

![BOM Hillarys](https://user-images.githubusercontent.com/26701506/103194803-abc9b600-491b-11eb-94f0-9d97708c28e6.JPG)
![BOM Swanbourne](https://user-images.githubusercontent.com/26701506/103194805-ad937980-491b-11eb-952f-b6fce063be0c.JPG)

**Comment by DavidFW1960** [comment]
Yes you can and quite easily. Just enter a Lat/Long for the station you want and create the observation sensors and say no for the forecast sensors. Then do the reverse for the forecast sensors...

**Comment by bremor** [comment]
Yup, just like @DavidFW1960 said, you will have to create multiple instances of the integration with different lat/lon. Let us know if you have trouble figuring it out.

**Comment by DavidWicks** [comment]
Thankyou, worked as suggested.
