### ISSUE TITLE
Icon Descriptor not matching up with  Short Text

### ISSUE THREAD

**Issue by DavidWicks** [bremor/bureau_of_meteorology#61]
![Bureau Of Meterology Descriptor](https://user-images.githubusercontent.com/26701506/103208234-16d6b500-493b-11eb-9cb5-a7963ac1b050.png)

**Comment by bremor** [comment]
Always mostly sunny! 😎 I think I want to live in Marmion. I’ll take a look at this, thanks for raising the issue

**Comment by bremor** [comment]
@DavidWicks  I'm not experiencing this issue... are you still seeing this?
![image](https://user-images.githubusercontent.com/34525505/104247273-8e6c1e80-54bb-11eb-814d-d96ec978a46e.png)
![image](https://user-images.githubusercontent.com/34525505/104247304-9f1c9480-54bb-11eb-8955-a0bba06bbecd.png)

**Comment by DavidWicks** [comment]
Yes I am.
![Icon Descriptor](https://user-images.githubusercontent.com/26701506/104400907-233f4c80-558e-11eb-9f4b-77ec9f7ba6a4.JPG)
![Short Text](https://user-images.githubusercontent.com/26701506/104400917-24707980-558e-11eb-9137-68a5b0648d6e.JPG)

**Comment by DavidFW1960** [comment]
I think that's always happened. The short text is like a summary and can be different to the icon descriptor.

**Comment by oneseventhree** [comment]
Same thing is happening with mine as well. It says today is just PARTLY CLOUDY but the icon shows RAINY even if there is no rain forecast today?

**Comment by bremor** [comment]
Can you guys please share your geohash with me? You can get it if you set logging to debug for this integration.
```
logger:
  default: warn
  logs:
    custom_components.bonaire_myclimate: debug
```
