### ISSUE TITLE
Fire Danger 0 Sensor regularly going  "unknown"

### ISSUE THREAD

**Issue by DavidWicks** [bremor/bureau_of_meteorology#65]
![Fire Danger 0  Regular Unknown](https://user-images.githubusercontent.com/26701506/103762157-c81fce00-5052-11eb-8b34-fb8c5ccb8f74.JPG)

**Comment by DavidFW1960** [comment]
let me guess.... around 10PM? It does seem to do that. It's BOM, not the integration doing this

**Comment by DavidWicks** [comment]
It is actually about 16:30 each day.  Would that still be BOM ? if so I will close the issue.

**Comment by DavidFW1960** [comment]
Yeah it's BOM but I think Brendon is writing a previous state now in the latest version so maybe fixed..

**Comment by bremor** [comment]
Yeah, BOM stop publishing the value, but I have tried to make it so my integration will retain the value when it disappears from BOM. So this is a bug. I am able to reproduce it too so will try and push out a patch soon.

**Comment by DavidFW1960** [comment]
Doing it this morning as well (I think it's BOM)
![image](https://user-images.githubusercontent.com/36390762/110717385-0ad17280-825d-11eb-81db-5f7155273f96.png)

**Comment by DeanoAus** [comment]
Hey all, firstly, love the plugin.

This happens for min temperature all the time for me as well. 

![image](https://user-images.githubusercontent.com/35859910/113466502-2577bf80-9488-11eb-9098-4ebc727dce0f.png)

**Comment by DavidFW1960** [comment]
This is a BOM issue, not an issue with this integration. For my weather card this is why I use a Template Sensor as BOM zeros some forecast sensors for the current day regularly.

**Comment by DeanoAus** [comment]
> This is a BOM issue, not an issue with this integration. For my weather card this is why I use a Template Sensor as BOM zeros some forecast sensors for the current day regularly.

Oh yeah, I realise it's the BOM, but could the integration store the last valid value perhaps?

**Comment by DavidFW1960** [comment]
I know Brendan was thinking about doing that but it's not even logical if you consider it. The minimum for the day is ~4am and after that time (or in the afternoon BOM makes it unavailable) So given by then you HAVE the actual observed minimum why do you care what the forecast was? This is why I use a Template sensor giving me the actual minimum for today.

**Comment by DeanoAus** [comment]
Actually, yeah, good point. I look at it in the evening to determine what the low point will be during the night for my animals, but at some point I figured it just swapped over to the next day. 

I'll have to look into templated sensors like you suggest.

**Comment by DeanoAus** [comment]
Actually, I just used a conditional card to swap between today and tomorrow when it returns unknown, thanks for the point in the right direction. :)

**Comment by DavidFW1960** [comment]
Yeah the Min_1 is actually the upcoming overnight temp and it will tick over to min_0 at midnight. Checking for unknown as you are is the way to go.

**Comment by cjsmns** [comment]
I'm also having the 'unknown' status for the last few days, but rather than just being at the end of the day, it's the whole day, like there is no info available or something.

I just had a look at the RFS ratings for today and it seems that the whole state is listed as None, but my status is Unknown.

**Comment by DeanoAus** [comment]
That's because NSW is out of the fire danger period and the BOM won't produce Fire Danger Ratings until October. They run Oct - March by default, but can be brought forward or extended based on needs.
(Ex employee).

**Comment by DavidFW1960** [comment]
They only publish a status in Summer.

**Comment by cjsmns** [comment]
Well, that's annoying, makes sense, but annoying.

Is it possible to update the plugin to reflect this? Maybe have it just default to None then or something?

For now I've just modified my conditional card to show the older fire ratings integration status if there is an unknown status.

**Comment by DavidFW1960** [comment]
Or use a Template sensor if you don't like unknown. Actually not Summer but Fire Season. The FRS site also doesn't show a status out of season either. (Just saw @DeanoAus response too..)

**Comment by cjsmns** [comment]
Ah right. Well, something to think about.

**Comment by ettiennegous** [comment]
> Hey all, firstly, love the plugin.
> 
> This happens for min temperature all the time for me as well.
> 
> ![image](https://user-images.githubusercontent.com/35859910/113466502-2577bf80-9488-11eb-9098-4ebc727dce0f.png)

I get the same thing too, Based on previous comments its a BOM issue, what is the workaround?

**Comment by DavidFW1960** [comment]
The work around is to use either the average or statistics sensors with a template sensor for whatever card you are using to display the minimum
