### ISSUE TITLE
hourly sensor data

### ISSUE THREAD

**Issue by fulhamhigh** [bremor/bureau_of_meteorology#66]
Hi - as a possible idea - would it be possible to add sensors for the hourly data that BOM now publishes in its API. e.g. https://api.weather.bom.gov.au/v1/locations/[your location geo hash]/forecasts/hourly

things like temp, chance of rain, and rain amount would be great to implement into homeassistant similar to the way that they are used in the BOM mobile app.

**Comment by bremor** [comment]
Definitely possible! I will look to include this at some point

**Comment by CuongHome** [comment]
Hourly would be much helpful, i am trying to automate hotwater to heat when the sun is out, so some prediction would be much helpful. thanks

**Comment by solrai38** [comment]
Rather than lots of individual sensors which could get messy, would this be better as attributes of the existing temperature sensor similar to how the Amber Electric integration returns the price forecasts?  This approach works well for a range of automations without too much 'noise'.

**Comment by blakeseufert** [comment]
@bremor, Is it possible for your integration to create another sensor that in addtion to your weather.location forecast we could have weather.local_hourly or something?

**Comment by bremor** [comment]
Ok guys :) Thanks for your request. I am going to pull my socks up and create this hourly forecast for you.

**Comment by blakeseufert** [comment]
You are a legend, where can i donate?

**Comment by bremor** [comment]
No need to donate, I also selfishly want hourly wind data so i can create an automation to let me know when it's a good time to go paddle boarding!

**Comment by bremor** [comment]
I have added an hourly forecast weather entity into v1.0.0, which is currently in Beta.

![image](https://user-images.githubusercontent.com/34525505/140291257-29a97d01-5686-4e97-be0e-28653ccb6f46.png)

**Comment by fulhamhigh** [comment]
This is awesome, thank you
