### ISSUE TITLE
Feature Idea: Historical Data

### ISSUE THREAD

**Issue by memphisraynz** [bremor/bureau_of_meteorology#67]
Is it posisble to have the option to have historical data like how much rainfall for the past x number of days.
Would be usefull for other automaiton, like if there has been less than 10mm of rain for the past 3 days, turn on the irrigation.

Cheers

**Comment by bremor** [comment]
I like this idea but I can't see how I could implement this.. the integration wouldn't be able to persist this data across reloads.

I use the 'rain_since_9am" in a graph to give a visual idea of how much rain has fallen recently... but it doesn't have an accumulated rain for the last 3 days for example. There might be a way to find this accumulated value using some kind of historical or statistics sensor or even a python_script, but I can't do it within this integration, sorry.

**Comment by DavidFW1960** [comment]
Definitely use history in HA for this. I use a custom average component that would work great for this exact task......

**Comment by memphisraynz** [comment]
Thanks, I'll have a look at the average component. I initially looked at Statistics but ran into an issue with the number of data points.

**Comment by bremor** [comment]
Thanks for the suggestion! Really appreciate it. Have a great day 👍
