### ISSUE TITLE
Icons and Short text states

### ISSUE THREAD

**Issue by oneseventhree** [bremor/bureau_of_meteorology#68]
Hi,
Do you have a list of all the MDI icons used and their descrption?. Kind of like:

```
    '1': 'mdi:weather-sunny',
    '2': 'mdi:weather-night',
    '3': 'mdi:weather-partly-cloudy',
    '4': 'mdi:weather-cloudy',
    '6': 'mdi:weather-sunset',
    '8': 'mdi:weather-partly-rainy',
    '9': 'mdi:weather-windy',
    '10': 'mdi:weather-sunset',
    '11': 'mdi:weather-rainy',
    '12': 'mdi:weather-pouring',
    '13': 'mdi:weather-sunset',
    '14': 'mdi:snowflake-melt',
    '15': 'mdi:weather-snowy',
    '16': 'mdi:weather-lightning',
    '17': 'mdi:weather-light-showers',
    '18': 'mdi:weather-pouring',
    '19': 'mdi:weather-hurricane'
```
as I need icons for:
partly-cloudy-night
fog
sleet
clear
night-clear

To use with my tileboard (https://github.com/resoai/TileBoard)

and lastly, do you have a list of all the "short text" desciption/states?

Thanks in advance!

**Comment by oneseventhree** [comment]
Hi,

Can anyone help me with this? I just came across a new one "mdi:weather-lightning-rainy" so a list would be great.

Thanks in advance :)

**Comment by bremor** [comment]
You can find the mapping values here, it shows all possible short text and what icon I have decided to map it to.
https://github.com/bremor/bureau_of_meteorology/edit/main/custom_components/bureau_of_meteorology/PyBoM/collector.py
