### ISSUE TITLE
LENGTH_MILLIMETERS?

### ISSUE THREAD

**Issue by Bazmundi** [bremor/bureau_of_meteorology#69]
home-assistant    | 2021-01-24 11:37:04 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform bureau_of_meteorology.sensor: Platform not found (cannot import name 'LENGTH_MILLIMETERS' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).
home-assistant    | 2021-01-24 11:37:04 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform bureau_of_meteorology.weather: Platform not found (cannot import name 'LENGTH_MILLIMETERS' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).

HA:
Home Assistant 0.114.4
Frontend version: 20200811.0 - latest

HA running on HYPRIOT in a docker container rather than using HASSIO.  I used docker exec -it <container> /bin/bash to jump into the container.  Indeed /usr/src/homeassistant/homeassistant/const.py does NOT contain a definition for LENGH_MILLIMETERS in the version of home-assistant I am running.  Not that keen to change versions at the mo as I have a home system up and running and the last HA upgrade I tried required rework and pain to get things up and running again.  

I am otherwise running off windows on a laptop without docker, so hooking up to a remoted docker container on the RPI from windows, using vscode tools, seems off the cards for the moment.

I cannot run or install nano into the HA container as is.  I guess I am looking at a hack of the BOM sensor.py as I can get to that outside the container in the local volume?

Cheers,
A

**Comment by Bazmundi** [comment]
DOH, same for PERCENTAGE.  Opted to change to UNIT_PERCENTAGE which is in the source constant file.

**Comment by bremor** [comment]
You need to be running 0.116 I think. You should probably upgrade anyway after the recent security issues.
