### ISSUE TITLE
is it possible to have some sort of state that shows if its sunny or not

### ISSUE THREAD

**Issue by dave-schwarz** [bremor/bureau_of_meteorology#72]
If its sunny, I'd like to close my curtains at specific azimuth's (so while working at home I dont have the sun shining on me)
However its almost impossible to see if its sunny or not from the states that come back.
My current rules are based on looking at the current state when I get to hot, and its getting ridiculous

here's the current version of rules

condition: and
conditions:
  - condition: numeric_state
    entity_id: sensor.sun_azimuth
    above: '180'
    below: '335'
  - condition: or
    conditions:
      - condition: state
        entity_id: weather.jan_juc
        state: Mostly sunny.
      - condition: state
        entity_id: weather.jan_juc
        state: sunny
      - condition: state
        entity_id: weather.jan_juc
        state: exceptional
      - condition: state
        entity_id: weather.jan_juc
        state: Showers. Windy.
      - condition: state
        entity_id: weather.jan_juc
        state: Showers increasing. Windy.
      - condition: state
        entity_id: weather.jan_juc
        state: Partly cloudy.
      - condition: state
        entity_id: weather.jan_juc
        state: Early shower. Sunny afternoon.
      - condition: state
        entity_id: weather.jan_juc
        state: Becoming sunny.
      - condition: state
        entity_id: weather.jan_juc
        state: Mostly clear.
      - condition: state
        entity_id: weather.jan_juc
        state: Cloud clearing.
      - condition: state
        entity_id: weather.jan_juc
        state: windy
  - condition: sun
    before: sunset

 
Not sure if this can be resolved or not :-)

**Comment by bremor** [comment]
Hey Dave, I’ve tried to do something similar to this in the past, what I used was ARPANSA which is great if you live in a capital city. They have UV detectors and publish their values on their website and also through an API. If you live near one of the sensors you may be able to use it to estimate current sun exposure. One problem I had with this data is it will fluctuate for example if a cloud rolls over.

https://www.arpansa.gov.au/our-services/monitoring/ultraviolet-radiation-monitoring/ultraviolet-radation-data-information

**Comment by DavidFW1960** [comment]
I started using a custom component (illuminate) that looks at the weather.home state provided by met.no (HA Default) as well as a Template Sensor using the weather condition from Brendans sensor = both guess the outside illuminance and I then use an automation to turn on an interior light at 4PM if the light is low. It actually works much better than I expected so perhaps you can use those for this purpose.

I provide the package and automation with my weather card and also if you look on my own github repo you can find it and see how I use it for this... Still tweaking but pretty happy so far.

**Comment by bremor** [comment]
Another option if you felt like a little bit of DIY, you could hook a LDR up to a raspberry pi or a NodeMCU and have it publish illuminance values to home assistant, if you could situate the device near a window or even outside.
https://www.amazon.com.au/s?k=Light+Dependent+Resistor&linkCode=ll2&linkId=6a316e975ca4d67443b30ee7f8da82a6&tag=pimylifeup-22&ref=as_li_ss_tl

**Comment by dave-schwarz** [comment]
thanks for all this, will need to have a local sensor I think

**Comment by bremor** [comment]
Another idea would be to get solar panels. You could use the energy generation to tell you if it’s sunny or not 😁

**Comment by dave-schwarz** [comment]
ha ha
