### ISSUE TITLE
Lost my sensors in the Newcastle region

### ISSUE THREAD

**Issue by PictureMil** [bremor/bureau_of_meteorology#73]
Hello. Firstly - I am very grateful for the work you have pit into this integration! I love it! Thanks!
I live in the suburb of Broadmeadow in Newcastle NSW. I am running the latest version. About 3 days ago I lost all me sensors with logs like:
```
Unexpected error fetching BOM observation Broadmeadow data: 'NoneType' object is not subscriptable
# and
Error adding entities for domain weather with platform bureau_of_meteorology
```
If I delete the integration and start from scratch; when I enter coordinates like:
```
-32.930893, 151.733315
```
The integration fails to setup and throws: 
```
Unknown Error
```
It seems to fail finding a nearby weather station. Maybe the data provided by BOM has changed somehow or our sensor is offline. Don't know exactly.

Can you help please?

**Comment by bremor** [comment]
It seems like your closest station is not providing a few things, you can even see it here:
https://weather.bom.gov.au/location/r65usv0-adamstown

Newcastle Nobbys stopped providing wind data on 1/Feb, 2:30 PM
http://www.bom.gov.au/products/IDN60901/IDN60901.94774.shtml

I can write an update to the integration to ignore this missing data and create the sensors with an unknown state. Might take me a couple of days though.

`{
   "metadata":{
      "response_timestamp":"2021-02-04T00:37:58Z",
      "issue_time":"2021-02-04T00:31:02Z"
   },
   "data":{
      "temp":24.3,
      "temp_feels_like":null,
      "wind":null,
      "gust":null,
      "rain_since_9am":0,
      "humidity":100,
      "station":{
         "bom_id":"061055",
         "name":"Newcastle Nobbys",
         "distance":5805
      }
   }
}`

`{"metadata":{"response_timestamp":"2021-02-04T00:37:37Z","issue_time":"2021-02-04T00:31:03Z"},"data":{"temp":22.1,"temp_feels_like":17.6,"wind":{"speed_kilometre":33,"speed_knot":18,"direction":"WNW"},"gust":{"speed_kilometre":43,"speed_knot":23},"rain_since_9am":0,"humidity":65,"station":{"bom_id":"023034","name":"Adelaide Airport","distance":2052}}}`

**Comment by PictureMil** [comment]
I don't want you to go any trouble if the BOM starts providing the info again. But I suppose if this sort of station outage creates errors for users trying to setup or retain stability - a code update might be wise.

In your experience could it just be an outage that will probably get restored in the coming period? I'll try to find a nearby station manually in the meantime.

Thanks for the swift response!

**Comment by PictureMil** [comment]
Looks like my weather station has started providing data again. So I can revert to my usual settings.

Like I said, it might be nice to have code that can handle a user attempting to install your integration; when parts of the data set are missing because of a temporary outage. I suppose it would be confusing for a newbie who is doing everything right encounters "unknown error".
