### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by brettlg** [bremor/bureau_of_meteorology#76]
Hi,  Apologies if this info is somewhere I have overlooked but I cannot see which entries I need to see info in Lovelace.  I am using yams mode.  Are there any screenshots available to show how data is presented?

I used the old BOM Radar image but have found this is broken on the latest HomeAssistant release.

Thanks

**Comment by nickdos** [comment]
You'll want a different repo for the radar image - see https://github.com/theOzzieRat/bom-radar-card

**Comment by DavidFW1960** [comment]
> Hi, Apologies if this info is somewhere I have overlooked but I cannot see which entries I need to see info in Lovelace. I am using yams mode. Are there any screenshots available to show how data is presented?
> 
> I used the old BOM Radar image but have found this is broken on the latest HomeAssistant release.
> 
> Thanks

You can use the inbuilt weather entity created via the integration for some cards whereas other cards use the sensors. You need to say which card you are using...
