### ISSUE TITLE
Provide minimum and maximum temperature values for forecast data

### ISSUE THREAD

**Issue by nickdos** [bremor/bureau_of_meteorology#79]
The BOM forecast I see on my phone (and can get via Willy Weather) includes daily minimum and maximum temperatures. It would great if this could be included in the forecast sensors similar to the `sensor.city_extended_text_0` and `sensor.city_short_text_0` sensors.

The [Willy Weather](https://github.com/safepay/sensor.willyweather) HACS project does this using a separate sensors: `sensor.ww_day_0_max_temp` and `sensor.ww_day_0_min_temp`.

**Comment by DavidFW1960** [comment]
These are included already if you turn them on when you add the integration (where you select the sensors you want)

**Comment by nickdos** [comment]
Thanks for pointing that out 👍
