### ISSUE TITLE
Is there a way to change settings?

### ISSUE THREAD

**Issue by nickdos** [bremor/bureau_of_meteorology#80]
Is there a way to modify the setting for this component (e.g. add in options I may have opted out of when first setting up the component). The docs don't mention this and I can't see a `configure` option in the integration screen for this component.

Before I go the nuclear route and remove the component and all associated entities, I wanted to check if there was a way to modify the settings, so as to avoid the (potential) duplicate sensor issue this often results in.

**Comment by DavidFW1960** [comment]
Just remove the component and add it back. (DON'T remove any entities)

**Comment by nickdos** [comment]
Yep that worked, although some of the sensors changed their names from when I first installed it, way back when the original BOM add-on was removed. So I had to fix a few Lovelace cards & automations - no big deal.
