### ISSUE TITLE
Wind Monitoring

### ISSUE THREAD

**Issue by Rolzzz** [bremor/bureau_of_meteorology#83]
Hello there!
I'd like to monitor the wind at a few locations, sadly I can't get it to work... it looked like previous versions of the BOM HA had the ability but I'm not sure how I can get personal sensors added in this one.

Do you have a suggestion how I can implements these sensors?

  - platform: bureau_of_meteorology
    station: IDQ60901.95591
    friendly_name: "Redcliffe"
    monitored_conditions:
      - wind_dir
      - wind_spd_kt
      - gust_kt
  - platform: bureau_of_meteorology
    station: IDQ60901.94590
    friendly_name: "Inner Beacon"
    monitored_conditions:
      - wind_dir
      - wind_spd_kt
      - gust_kt
  - platform: bureau_of_meteorology
    station: IDQ60901.94578
    friendly_name: "Brisbane Airport"
    monitored_conditions:
      - wind_dir
      - wind_spd_kt
      - gust_kt
  - platform: bureau_of_meteorology
    station: IDQ60901.9949
    friendly_name: "Hope Banks Beacon"
    monitored_conditions:
      - wind_dir
      - wind_spd_kt
      - gust_kt
  - platform: bureau_of_meteorology
    station: IDQ60901.94591
    friendly_name: "Banana Bank"
    monitored_conditions:
      - wind_dir
      - wind_spd_kt
      - gust_kt
  - platform: bureau_of_meteorology
    station: IDQ60901.94580
    friendly_name: "Gold Coast Seaway"
    monitored_conditions:
      - wind_dir
      - wind_spd_kt
      - gust_kt

**Comment by DavidFW1960** [comment]
You don't use yaml to configure the new component - all is done in the GUI and you just add the integration multiple times to add extra locations.

**Comment by Rolzzz** [comment]
> You don't use yaml to configure the new component - all is done in the GUI and you just add the integration multiple times to add extra locations.

but it's forcing me to input a GPS location which is not what I want... I'd like to specify the actual stations and I don't have the GPS coordinates of them.
I have a weather station at my place so I'm not after my conditions.

**Comment by DavidFW1960** [comment]
Use google to get the gps coordinates for the locations you want to use. It will then tell you the location of the stations.

**Comment by Rolzzz** [comment]
> Use google to get the gps coordinates for the locations you want to use. It will then tell you the location of the stations.

yeah not working to how I envisaged, never mind, will look for alternatives.
cheers
