### ISSUE TITLE
BOM API for rain radar

### ISSUE THREAD

**Issue by roly151** [bremor/bureau_of_meteorology#84]
Hi, This is not an issue with your work, but I also use the BOM API for a rain radar in an app. A day ago I started getting 404 errors for the rain tiles. Have you experienced this? If not, would it be possible to chat with you about the tiles?

**Comment by DavidFW1960** [comment]
BOM changed the address. There is a BOM Radar card and Simon updated it for the new URL for the tiles today. There is a thread on the forum for Simons card

**Comment by roly151** [comment]
Really appreciate the quick reply! Have found the thread.
