### ISSUE TITLE
Wind Speed not showing correctly/Showing knots instead of kmph(?)

### ISSUE THREAD

**Issue by oneseventhree** [bremor/bureau_of_meteorology#86]
Hi,

First of all thanks for a great integration!

I've noticed that my windspeed is never right. BOM Shows 17kmph(9 knots):
<img width="419" alt="Screen Shot 2021-11-01 at 3 47 07 pm" src="https://user-images.githubusercontent.com/15043282/139623070-770e5eec-4d36-4c1f-9a80-8971468bd33d.png">

but the integration shows 9kmph:
<img width="414" alt="Screen Shot 2021-11-01 at 3 47 51 pm" src="https://user-images.githubusercontent.com/15043282/139623093-a16c7291-7da7-42e7-9eda-62c843675e57.png">

Could this just be an error of the integration pulling the knots instead?

Thanks!

**Comment by DavidFW1960** [comment]
It should have both.. knots and km/h in seperate sensors. (Mine does) Yoe appear to be using a template for that wind speed as it's a numberless state in HA without the direction or unit (the unit is an attribute of the entity) This looks self inflicted to me?

**Comment by oneseventhree** [comment]
> It should have both.. knots and km/h in seperate sensors. (Mine does) Yoe appear to be using a template for that wind speed as it's a numberless state in HA without the direction or unit (the unit is an attribute of the entity) This looks self inflicted to me?

Hi David,

I am not sure what you mean? I haven't made a template for this integration.
The weather.fitzroy entity was made by the integration:
<img width="785" alt="Screen Shot 2021-11-01 at 4 57 25 pm" src="https://user-images.githubusercontent.com/15043282/139628018-a6dc074e-9c1d-43c4-b8fa-4027597d616b.png">

and looks like this in Developer > States tab:
<img width="1054" alt="Screen Shot 2021-11-01 at 4 55 15 pm" src="https://user-images.githubusercontent.com/15043282/139627885-7449a03f-9475-480a-9f0c-2acc422f2619.png">


I have a kmph for the observation tower but not for my suburb:
<img width="1023" alt="Screen Shot 2021-11-01 at 4 56 31 pm" src="https://user-images.githubusercontent.com/15043282/139627955-f537f7ea-a1ff-4494-b57e-09ee69fc85d2.png">

**Comment by DavidFW1960** [comment]
So where did the screenshot from your original post originate? It is totally different to the last shots.
One is the weather entity and the second one is the sensor and you can see that neither of them show any dimension for the value.
The way the integration works is it will pick the nearest observation tower for the observations (NOT your suburb) The forecast is an interpolation for your suburb from all the surrounding stations.
But none of the screenshots except your original post show any unit for the wind speed (which is correct if you look at the states and attributes) They are dimensionless. So you have something creating the screenshot in first post and that is where the error is.
You should see 4 sensors. 2 for speed and 2 for gust one in knots and one in km/h

**Comment by DavidFW1960** [comment]
it might be the weather card you are using assuming the wrong unit?

**Comment by oneseventhree** [comment]
> So where did the screenshot from your original post originate? It is totally different to the last shots. One is the weather entity and the second one is the sensor and you can see that neither of them show any dimension for the value. The way the integration works is it will pick the nearest observation tower for the observations (NOT your suburb) The forecast is an interpolation for your suburb from all the surrounding stations. But none of the screenshots except your original post show any unit for the wind speed (which is correct if you look at the states and attributes) They are dimensionless although for the weather entity there is an attribute that shows the unit. So you have something creating the screenshot in first post and that is where the error is. You should see 4 sensors. 2 for speed and 2 for gust one in knots and one in km/h

The first shot is a screen shot of when I click the (i) button under the entity name in Developer Tools > States:
<img width="783" alt="Screen Shot 2021-11-01 at 6 15 37 pm" src="https://user-images.githubusercontent.com/15043282/139635447-58870ba5-f6c5-4268-9410-e5a045ca6158.png">

**Comment by DavidFW1960** [comment]
Ah so home assistant when you click on i is showing the weather entity not the sensor entity. Are you saying 11km/h should be 11 knots? What do the 4 sensors show?

**Comment by oneseventhree** [comment]
> Ah so home assistant when you click on i is showing the weather entity not the sensor entity. Are you saying 11km/h should be 11 knots? What do the 4 sensors show?

I think the integration updates faster/delayed than the BOM website - Screenshots were taken at the same time
11kmph:
<img width="410" alt="Screen Shot 2021-11-02 at 11 48 09 am" src="https://user-images.githubusercontent.com/15043282/139769273-0c72082d-4014-4c7f-b60f-2ce13a7cf13e.png">

15kmph:
<img width="179" alt="Screen Shot 2021-11-02 at 11 48 18 am" src="https://user-images.githubusercontent.com/15043282/139769294-fb7a3199-b026-4135-8df6-37a02e01643f.png">

**Comment by DavidFW1960** [comment]
You still haven't shown the HA sensors at the same time as the weather entity.
It *might* be it using the knots instead of km/h so Brendan could be parsing the wrong number to the weather entity (which is dimensionless and the HA weather obviously is expecting km/h) but you're not showing enough info to see if that is what is happening.

**Comment by oneseventhree** [comment]
> You still haven't shown the HA sensors at the same time as the weather entity. It _might_ be it using the knots instead of km/h so Brendan could be parsing the wrong number to the weather entity (which is dimensionless and the HA weather obviously is expecting km/h) but you're not showing enough info to see if that is what is happening.

Do you mean this sensor:
<img width="993" alt="Screen Shot 2021-11-02 at 2 43 42 pm" src="https://user-images.githubusercontent.com/15043282/139783642-c10c9382-0c05-422b-8081-18485836e9c8.png">

Thats the only entity that shows wind speed

**Comment by DavidFW1960** [comment]
no that is the weather entity, not the sensor.
This is a sensor:
![image](https://user-images.githubusercontent.com/36390762/139784418-d8337c7d-d31b-4137-b9b5-c9287c0cd04d.png)
You posted that above and as I said there are 4

**Comment by oneseventhree** [comment]
> no that is the weather entity, not the sensor. This is a sensor: ![image](https://user-images.githubusercontent.com/36390762/139784418-d8337c7d-d31b-4137-b9b5-c9287c0cd04d.png) You posted that above and as I said there are 4

thats the entity of the observation tower and not my suburb/location:
<img width="1016" alt="Screen Shot 2021-11-02 at 2 56 36 pm" src="https://user-images.githubusercontent.com/15043282/139784643-ae84c172-c0cf-4038-a3d8-fc03d5df6106.png">

**Comment by DavidFW1960** [comment]
As I already explained to you, there are ONLY observations for the observation tower. There are NO observations for your location. There can be forecasts but not observations.

**Comment by bremor** [comment]
Thanks for the investigation. Looking at my location, it is behaving as expected. wind speed sensors are 2 knots and 4 km/h, and the weather entity is showing windspeed of 4km/h
![image](https://user-images.githubusercontent.com/34525505/140045637-4b2e998d-d42b-47fc-a88a-3010de27963f.png)

Do your comparison to this website instead, this is where my integratoin pulls the data from:
https://weather.bom.gov.au/

I am experiencing the same discrepency as you if I use this weird Beta site.
 http://www.bom.gov.au/places/vic/fitzroy/
