### ISSUE TITLE
Barometric pressure

### ISSUE THREAD

**Issue by geejayem99** [bremor/bureau_of_meteorology#9]
Is barometric pressure available in the data you're getting at all. I know some locations don't have it under the old integration, but I'm in Mount Gambier and it shows under the old integration, but not on this one.

I looked at the page you directed someone else to (for the cloud cover query) and don't see pressure there, for Mount Gambier or any of the major cities, so I'm guessing it's not going to be there. Seems like an odd thing for them to omit from a weather page.

**Comment by DavidFW1960** [comment]
It's not available in the new API

**Comment by geejayem99** [comment]
OK, thanks.
