### ISSUE TITLE
Tile showing m/s in lieu of kmh or kph

### ISSUE THREAD

**Issue by pvanleen** [bremor/bureau_of_meteorology#94]
Hi,

Although I just upgraded to 1.1.1 since the previous version (from what I can tell) the tile showing BOM info is showing m/s under the current temp instead of kph however the data from entities page lists it as kph.

![image](https://user-images.githubusercontent.com/93765335/147713589-d3dd126f-2d88-4e1e-9c85-7cd6a2b71c5a.png)

**Comment by DavidFW1960** [comment]
this looks like whatever card you are using is hard coded to show m/s. this isn't an issue with this integration it's a lovelace card issue and should be raised there. The weather entity from this integration and also met.no is dimensionless too BYW

**Comment by Makin-Things** [comment]
This is a card issue and has nothing to do with the integration.
