### ISSUE TITLE
Update version number in manifest.json

### ISSUE THREAD

**Issue by joe-sydney** [bremor/bureau_of_meteorology#98]
Just a minor thing, but I noticed that the version number in manifest.json has been on 0.10.3 for the past few releases:   "version": "0.10.3",

I went into the installed manifest.json to see if I needed to update the component, comparing it with the latest 1.1.1. Then I checked the version that come with 1.1.1 and it was 0.10.3. Perhaps I had the latest version all along?!! :)

Thanks for this very useful integration!

**Comment by Makin-Things** [comment]
This will be updated in future releases.

**Comment by Makin-Things** [comment]
Addressed in 1.1.2
